#!/usr/bin/env python3
"""Emit a Verilator blackbox stub (module header + empty body) for one module,
extracted verbatim from its real source.

Lets us lint OUR wrapper RTL (nanosoc_eth_chiplet, tidechart_shim) in isolation
without compiling the full SoC / TideLink / TideChart hierarchies. The stub keeps
the real port directions and widths, so Verilator's driven/undriven and width
analysis on the wrapper's own nets stays correct; it drops the body, so no
vendor behaviour and no submodule dependencies come along.

Reads only; never writes to the source (important: several sources live under
the READ-ONLY Arm IP tree). Emit to stdout:

    gen_bbox.py <module_name> <source.sv> > stub.sv

A joint work commissioned on behalf of SoC Labs, under Arm Academic Access license.
Copyright 2026, SoC Labs (www.soclabs.org)
"""
import os
import re
import sys


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)  # block comments
    text = re.sub(r"//[^\n]*", "", text)                      # line comments
    return text


def extract_header(name: str, text: str) -> str:
    """Return 'module NAME ... );' — the module keyword through the ';' that
    terminates the (optional #()-parameter and) port list, at paren depth 0.

    NOT SIMPLY "THE FIRST DEPTH-0 SEMICOLON". A package-import clause is legal
    between the module name and the port list, and it ends in a depth-0 ';' of
    its own:

        module foo import my_pkg::*; (input a, output b);

    Stopping there returns `module foo import my_pkg::*;`, and the caller then
    prints `endmodule` after it and exits 0 — A STUB WITH NO PORTS AT ALL,
    generated silently from a module that has plenty. None of the three
    blackboxed sources currently imports a package, but the failure is silent,
    so handle the construct here as gen_bbox_any.py does.
    """
    text = strip_comments(text)
    m = re.search(r"\bmodule\s+" + re.escape(name) + r"\b", text)
    if not m:
        sys.exit(f"gen_bbox: module '{name}' not found in source")
    i = m.start()
    depth = 0
    seg = m.end()                       # start of the text since the last ';'
    for j in range(i, len(text)):
        c = text[j]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        elif c == ";" and depth == 0:
            if re.search(r"\b(import|export)\b", text[seg:j]):
                seg = j + 1             # that ';' closed an import clause
                continue
            return text[i:j + 1]
    sys.exit(f"gen_bbox: unterminated header for '{name}'")


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    name, src = sys.argv[1], sys.argv[2]
    with open(src) as f:
        header = extract_header(name, f.read())
    # POST-CONDITION ON THE ARTEFACT, not on the parse having "worked".
    #
    # The whole value of this stub is that it "keeps the real port directions and
    # widths, so Verilator's driven/undriven and width analysis on the wrapper's
    # own nets stays correct" (docstring above). A stub that lost its ports keeps
    # none of that, and it is not obviously broken downstream: a body-less module
    # already suppresses UNDRIVEN and UNUSED (below), and this flow WAIVES both
    # codes anyway, so an emptied stub degrades quietly rather than loudly.
    # Refuse to emit one. verif/lint/run.sh treats a non-zero generator as a
    # skipped pass, and a skipped pass now fails the run.
    if "(" not in header and os.environ.get("GEN_BBOX_ALLOW_PORTLESS") != "1":
        sys.exit(f"gen_bbox: extracted a PORTLESS header for '{name}' from "
                 f"{src}:\n  {header.strip()[:200]}\n"
                 f"  A stub with no ports silently disables the driven/undriven "
                 f"and width analysis this\n  stub exists to preserve. If '{name}' "
                 f"genuinely has no ports, set GEN_BBOX_ALLOW_PORTLESS=1.")
    print(f"// AUTO-GENERATED blackbox stub for {name}")
    print(f"// derived (read-only) from {src}")
    print("// DO NOT EDIT, DO NOT COMMIT -- regenerated by verif/lint/run.sh")
    # A body-less stub leaves its outputs undriven and its inputs unread; both
    # are expected for a blackbox. These codes exist in Verilator 4.028.
    print("/* verilator lint_off UNDRIVEN */")
    print("/* verilator lint_off UNUSED */")
    print(header)
    print("endmodule")


if __name__ == "__main__":
    main()
