#!/usr/bin/env python3
"""Emit a lint blackbox for a hard macro, derived read-only from its vendor
Verilog model.

Keeps ONLY the module header, its `parameter` declarations and its
input/output/inout declarations (plus the `ifdef guards around them, so the
POWER_PINS variant stays correct). Drops the body: the behavioural model is a
simulation artifact (specify blocks, timing checks, X-propagation) that neither
synthesis nor lint should be reading, and these are compiled hard macros -- the
netlist binds a .lib/.lef, not RTL.

    gen_macro_bbox.py <module> <vendor_model.v> > stub.v

Never writes to the source. Copyright 2026, SoC Labs (www.soclabs.org)
"""
import re
import sys

DECL = re.compile(r"^\s*(module|parameter|localparam|input|output|inout)\b")
# First line of the behavioural body. Everything from here on is dropped -- and
# the scan STOPS, so a `task`/`function` argument (which is also spelled
# `input foo;`) can never be mistaken for a module port.
BODY = re.compile(r"^\s*(reg|wire|tri|integer|real|genvar|event|time|always|"
                  r"initial|assign|task|function|specify|defparam|supply[01])\b")


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    name, src = sys.argv[1], sys.argv[2]
    lines = open(src, errors="replace").read().splitlines()

    # Locate the module: first line declaring it, and the endmodule that closes it.
    mre = re.compile(r"^\s*module\s+" + re.escape(name) + r"\b")
    starts = [i for i, l in enumerate(lines) if mre.match(l)]
    if not starts:
        sys.exit(f"gen_macro_bbox: module '{name}' not found in {src}")
    first = starts[0]
    # Walk back over a preceding `ifdef/`ifndef guard so both header variants survive.
    lo = first
    for j in range(first - 1, max(-1, first - 4), -1):
        if re.match(r"^\s*`(ifdef|ifndef)\b", lines[j]):
            lo = j
            break
    hi = next((i for i in range(first, len(lines))
               if re.match(r"^\s*endmodule\b", lines[i])), None)
    if hi is None:
        sys.exit(f"gen_macro_bbox: no endmodule for '{name}' in {src}")

    out, i = [], lo
    while i < hi:
        line = lines[i]
        if BODY.match(line):
            break
        if line.lstrip().startswith("`"):
            # Preprocessor directive: keep only the conditional skeleton, so an
            # `include or `define from the model body cannot leak in.
            if re.match(r"^\s*`(ifdef|ifndef|else|elsif|endif)\b", line):
                out.append(line)
            i += 1
            continue
        if DECL.match(line):
            # Keep the whole construct, which may wrap, up to its ';'.
            while True:
                out.append(lines[i])
                if ";" in lines[i]:
                    break
                i += 1
                if i >= hi:
                    break
            i += 1
            continue
        i += 1

    # Balance any conditional left open by stopping at the body.
    depth = 0
    for l in out:
        if re.match(r"^\s*`(ifdef|ifndef)\b", l):
            depth += 1
        elif re.match(r"^\s*`endif\b", l):
            depth -= 1
    out += ["`endif"] * max(0, depth)

    # A stub that silently loses a port would make every net on it look undriven
    # at the instantiation site. Assert every header port got a direction.
    hdr = " ".join(out[:out.index(next(l for l in out if ");" in l or l.rstrip().endswith(";"))) + 1])
    body_txt = "\n".join(out)
    ports = set()
    for m in re.finditer(r"^\s*module\s+" + re.escape(name) + r"\s*\((.*?)\)\s*;",
                         "\n".join(out), re.S | re.M):
        ports |= {p.strip() for p in m.group(1).split(",") if p.strip()}
    declared = set(re.findall(
        r"^\s*(?:input|output|inout)\b[^;]*?([A-Za-z_][A-Za-z_0-9$]*)\s*;",
        body_txt, re.M))
    missing = ports - declared
    if missing:
        sys.exit(f"gen_macro_bbox: '{name}' ports without a direction "
                 f"declaration: {sorted(missing)} -- refusing to emit a stub "
                 f"that would drop them")

    print(f"// AUTO-GENERATED lint blackbox for '{name}'")
    print(f"// derived (read-only) from {src}")
    print("// DO NOT EDIT, DO NOT COMMIT -- regenerated by the full-lint runner.")
    print("// Hard macro: the netlist binds a compiled .lib/.lef, never this RTL.")
    print("/* verilator lint_off UNDRIVEN */")
    print("/* verilator lint_off UNUSED */")
    print("\n".join(out))
    print("endmodule")


if __name__ == "__main__":
    main()
