#!/usr/bin/env python3
"""Emit lint blackboxes for EVERY module in a source file.

Why real stubs and not `lint_off -file`: Verilator 4.028 applies the config
file's file filter at parse time only. The V3-stage checks -- UNOPTFLAT,
COMBDLY, BLKANDNBLK -- are emitted after that filter and leak straight through
it (measured: 10 findings from the Arm IP trees survived a `lint_off -file`
over those exact paths). The only way to keep vendor IP out of a lint report is
to keep it out of the front end.

Keeps, per module: the complete header -- `#(parameters)`, `import pkg::*;` and
the port list -- plus, for a non-ANSI (Verilog-1995) header, the
parameter/localparam and input/output/inout declarations that follow it. Drops
the body.

    gen_bbox_any.py <source> > stubs.sv

Never writes to the source -- several inputs live under the READ-ONLY Arm IP
tree. Copyright 2026, SoC Labs (www.soclabs.org)
"""
import re
import sys

MODULE = re.compile(r"^[ \t]*module\s+([A-Za-z_][A-Za-z_0-9$]*)", re.M)
DECL = re.compile(r"^\s*(parameter|localparam|input|output|inout)\b")
BODY = re.compile(r"^\s*(reg|wire|logic|bit|tri|integer|real|genvar|event|time|"
                  r"always|always_ff|always_comb|always_latch|initial|assign|task|"
                  r"function|specify|defparam|generate|supply[01]|typedef|import)\b")
COND = re.compile(r"^\s*`(ifdef|ifndef|else|elsif|endif|include|define|undef)\b")


def blank_comments(text):
    """Blank out comments, preserving every newline so offsets stay usable."""
    def repl(m):
        return re.sub(r"[^\n]", " ", m.group(0))
    text = re.sub(r"/\*.*?\*/", repl, text, flags=re.S)
    text = re.sub(r"//[^\n]*", repl, text)
    return text


def skip_ws(t, i):
    while i < len(t) and t[i].isspace():
        i += 1
    return i


def match_parens(t, i):
    """t[i] must be '('. Return index just past the matching ')'."""
    depth = 0
    while i < len(t):
        if t[i] == "(":
            depth += 1
        elif t[i] == ")":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise ValueError("unbalanced parentheses")


def header_end(t, after_name):
    """Index just past the ';' that terminates a module header.

    Handles, in any order: `#(...)` parameter port list, `import pkg::*;`
    (whose ';' is NOT the header terminator), and the `(...)` port list.
    """
    i = after_name
    while True:
        i = skip_ws(t, i)
        if i >= len(t):
            raise ValueError("unterminated module header")
        if t[i] == "#":
            j = skip_ws(t, i + 1)
            i = match_parens(t, j)
        elif t[i] == "(":
            i = match_parens(t, i)
        elif t.startswith("import", i):
            i = t.index(";", i) + 1
        elif t[i] == ";":
            return i + 1
        else:
            # An attribute (* ... *) or a stray token; step over one char.
            i += 1


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = sys.argv[1]
    raw = open(src, errors="replace").read()
    t = blank_comments(raw)

    spans = []
    for m in MODULE.finditer(t):
        name = m.group(1)
        try:
            he = header_end(t, m.end())
        except ValueError as e:
            sys.exit(f"gen_bbox_any: {src}: module '{name}': {e}")
        em = re.compile(r"^[ \t]*endmodule\b", re.M).search(t, he)
        end = em.start() if em else len(t)
        spans.append((name, m.start(), he, end))
    if not spans:
        sys.exit(f"gen_bbox_any: no module in {src}")

    print(f"// AUTO-GENERATED lint blackbox(es), read-only, from {src}")
    print("// DO NOT EDIT, DO NOT COMMIT -- regenerated by the full-lint runner.")
    print("/* verilator lint_off UNDRIVEN */")
    print("/* verilator lint_off UNUSED */")
    print("/* verilator lint_off WIDTH */")
    # One stub file holds every module from its source, so its name matches at
    # most one of them. That is a property of this generator, not of the design.
    print("/* verilator lint_off DECLFILENAME */")
    for name, s, he, end in spans:
        header = raw[s:he]
        print(header)
        # Non-ANSI header: the directions live after it. Keep declarations (and
        # the `ifdef skeleton around them) until the body starts.
        if not re.search(r"\b(input|output|inout)\b", header):
            lines = raw[he:end].splitlines()
            i = 0
            while i < len(lines):
                line = lines[i]
                if BODY.match(line):
                    break
                if COND.match(line):
                    print(line)
                elif DECL.match(line):
                    while True:                      # declarations can wrap
                        print(lines[i])
                        if ";" in lines[i] or i + 1 >= len(lines):
                            break
                        i += 1
                i += 1
        print("endmodule")
    print(f"// {len(spans)} module(s): {', '.join(n for n, _, _, _ in spans)}")


if __name__ == "__main__":
    main()
