// -----------------------------------------------------------------------------
// GENERATED by verif/lint/full/merge_hal_rules.py -- DO NOT EDIT BY HAND.
// Union of every unit-level lint/hal.tcl in the integration, MINUS the sign-off
// rules, which may never be waived at any level:
//     CLKDMN CMBCDC GLTASR INSYNC LATINF MLTDRV NODRIV RSTSCB SIZMIS UNCONI
// hal_lint.sh preflights this file against that list and refuses to run if one
// reappears. Re-generate after changing any unit ruleset:
//     python3 verif/lint/full/merge_hal_rules.py
// -----------------------------------------------------------------------------

// ===== from nanosoc-multicore-system/lint/hal.tcl  (87 rule(s))
// HAL rule configuration for the NanoSoC Ethernet + Flash System lint flow
// Waives rules that conflict with AHB/AMBA/APB naming conventions or are
// style-only and not relevant to design correctness. Shared across all
// modules (ethmac_subsystem_apb, phc_ahb, top_ahb_qspi, sldma230,
// nanosoc_multicore). Module-specific waivers (e.g. QSPI SCLK CDC, DMA-230
// scan paths) should live alongside module RTL under lint/waivers/ and be
// pulled in with an additional -file on the command line when needed.
// Contributors
// David Mapstone (d.a.mapstone@soton.ac.uk)
// Copyright 2026, SoC Labs (www.soclabs.org)
// -- Naming convention waivers --------------------------------------
// AHB/APB signal names (hclk, hresetn, hsel, apbs_psel, etc.) are
// defined by the AMBA spec and cannot follow HAL's default suffixes.
-nocheck INPTNM
-nocheck OUTPNM
-nocheck CLKSNM
-nocheck RSTNAM
-nocheck MODLNM
-nocheck RGOPNM
-nocheck IDLENG
// Uppercase variable names -- CMSDK IP uses ALL-CAPS ports (HCLK, HADDR, etc.)
-nocheck LCVARN
// -- Style waivers --------------------------------------------------
// Numeric literals in port widths (e.g. [31:0]) are standard practice
-nocheck STYVAL
// Line length -- 120 chars is acceptable for modern editors
-nocheck MAXLEN
// Per-port and per-signal comments are overkill for clear code
-nocheck COMIOP
-nocheck COMDEC
-nocheck COMEND
// Always-block comments -- not required for well-structured code
-nocheck COMBLK
// Parameter base/width -- defaults are fine for simple integer params
-nocheck PRMVAL
-nocheck PRMBSE
// Compiler directives (`ifdef/`endif) -- used in CMSDK IP, acceptable
-nocheck CDWARN
-nocheck COMDIR
// Block labels -- meaningful code structure over mandatory labelling
-nocheck NOBLKN
// Missing begin/end in single-statement if/always -- acceptable style
-nocheck NBGEND
// Empty default case statements -- intentional no-op for completeness
-nocheck EMPSTM
// Numeric suffix in identifiers (e.g. pending_0, interrupt_1) -- by design
-nocheck NUMSUF
// Separate line for each signal declaration -- acceptable grouping
-nocheck SEPLIN
// -- Structural waivers --------------------------------------------
// Tied outputs are by design (zero-wait-state AHB/APB slaves)
-nocheck TIELOG
// Feedthrough paths are intentional (bus bridges, register files)
-nocheck FDTHRU
// Mixed sync/async is expected with async active-low reset (hresetn)
-nocheck SYNASN
// Combinational paths crossing hierarchy -- expected in layered bus designs
-nocheck CBPAHI
// Combinational outputs at top level -- AHB/APB protocols are comb by design
-nocheck TPOUNR
-nocheck SYNPRT
// Large operand arithmetic -- inherent to parameterised widths
-nocheck LRGOPR
// Potential overflow -- intentional wrapping for counters / FIFO pointers
-nocheck POIASG
// Multiple non-blocking assigns -- set/clear pattern for pending regs
-nocheck MULNBA
// Parameters in port expressions -- localparam addresses passed to sub-blocks
-nocheck PRMEXP
-nocheck IPRTEX
// FSM modelling style -- HAL expects specific patterns, ours are valid
-nocheck BADFSM
-nocheck EXTFSM
-nocheck TRNMBT
-nocheck STMCNM
// Typedef not in package -- module-local typedefs are acceptable
-nocheck TDOPKG
// Lowercase type names -- SV convention for types
-nocheck UCCONN
// Clock/reset renamed across CMSDK hierarchy (hclk->HCLK, hresetn->HRESETn)
-nocheck DIFCLK
-nocheck DIFRST
// Aliased wires -- read/write target share same expression by design
-nocheck DALIAS
// FF with constant data -- reset_n_d1 tied to 1 for deassertion detection
-nocheck FFCSTD
// FF without synchronous reset -- async reset is sufficient
-nocheck FFWNSR
// Mixed driver types on vector -- init vs runtime, harmless
-nocheck DFDRVS
// Unused port bits -- AHB htrans[0], upper address bits not decoded, etc.
-nocheck USEPRT
// Unconnected output naming -- debug signals don't need _nc suffix
-nocheck UCOPNM
// Unconnected output ports -- debug signals for cocotb probing only
-nocheck UNCONO
// Unread local registers -- debug signal aliases for testbench visibility
-nocheck URDREG
// Unread local wires -- intentional dead-end sinks for unused output ports
// routed to named `*_nc` wires per sys_desc/nanosoc_multicore_soc.yaml +
// scripts/patch_ahb_to_apb.py so design intent is explicit at the SoC top:
//   u_dap_ss_0     SoC-400 SWJ-DP wrapper:  cdbgpwrupreq / csyspwrupreq /
//                                           cdbgrstreq / jtagnsw / jtagtop
//   u_cpu_ss_1     chip-control nanosoc_ss_cpu PMU/sleep/local-clk sideband
//   u_phc_0        TideLink-future hardware-capture source 0
//   u_*_apb_bridge cmsdk_ahb_to_apb APBACTIVE / PSTRB / PPROT outputs
// Also masks AMBA tie-off bits (e.g. hresp[1] reserved per spec) and
// per-master `hmaster_*` debug aliases emitted by the interconnect
// generator. URDREG (the register counterpart) is already waived above.
// *** NARROWED 2026-08-09 -- DO NOT RESTORE THE BLANKET `-nocheck URDWIR`. ***
// The justification above is written entirely about NAMED dead-end sinks, but
// `-nocheck` is by rule name, not by pattern, so the waiver silenced EVERY
// unread wire in the design. It hid a real one: `dmac_0_err_w` in the SoC top
// is not a sink at all -- it is the DMA-250 error output, and it reaches no
// interrupt bus and no event router, so firmware can only see a DMA error by
// polling. That is exactly the finding this rule exists to raise, and the
// waiver's own recorded reason does not cover it.
// The two dead-end-sink conventions actually used in this tree are:
//   `*_nc`      70 in build_soc/rtl/nanosoc_multicore_soc.sv -- generator-
//               emitted open outputs (the list above)
//   `_unused*`  12 hand-RTL tie-off reductions of the form
//               `wire _unused = &{1'b0, HSIZE, HBURST, ...};`
// Both are covered by the pattern-scoped waiver in lint/hal_design_info.txt;
// anything else now reports. HAL cannot express a pattern in a `-file` rules
// file (`-nocheck` takes no qualifier), so the narrowed form lives in a
// design-info file and needs `-design_info` on the command line -- see
// lint/Makefile. If you are merging this ruleset into an integration-level
// set, you must carry the design-info file across too, or URDWIR comes back
// blanket-off.
// -nocheck URDWIR      <-- deliberately removed; see lint/hal_design_info.txt
// Glue logic at top level -- expected for address derivation wires
-nocheck ATLGLC
// CMSDK-specific warnings that leak through
-nocheck OLDALW
-nocheck LOGNEG
-nocheck LOGAND
-nocheck BOUINC
-nocheck MEMRNM
-nocheck MICAWS
-nocheck BBXSIG
// -- Third-party IP waivers (Cortex-M0 + CG092 cache + OpenCores MAC) ------
// Clock-domain crossings inside Arm Cortex-M0 IP are properly synchronised
// by `cm0_dbg_reset_sync`, `cm0_dap_cdc_*` cells, and the CG092 flash cache
// is a dual-clock SRAM with explicit synchronisers. HAL's CLKDMN flagging
// doesn't recognise these in-IP patterns — waive at the shared-ruleset
// level. (CDC is covered separately by SpyGlass.)
// DROPPED (sign-off rule, never waivable): -nocheck CLKDMN
// DROPPED (sign-off rule, never waivable): -nocheck INSYNC
// Combinational logic in asynchronous set/reset path — the Cortex-M0
// RSTBYPASS mux is standard behaviour in `cm0_rst_sync.v`.
// DROPPED (sign-off rule, never waivable): -nocheck GLTASR
// Missing default case in third-party `wb_slv_wrapper` / `apb_qspi_regs`.
-nocheck CDEFNC
// Duplicate case codes (OpenCores MAC register decoder uses style below).
-nocheck VERCAS
// "Unreachable state" flags in third-party FSMs — by design (sentinel states).
-nocheck UNRCHS
// -- Generated-top waivers (hierarchical SoC from nanosoc_gen) --------------
// nanosoc_gen emits `.in` / `.out` ports on empty glue instances when
// a feature is disabled (e.g. no dma230_req sources yet); fill is via
// explicit constants at integration time.
// DROPPED (sign-off rule, never waivable): -nocheck UNCONI
// Generator emits wide/narrow port connections depending on parameter
// overrides (e.g. HADDR[APB_ADDR_W-1:0]); harmless once the overrides
// are consistent across subsystems.
// DROPPED (sign-off rule, never waivable): -nocheck SIZMIS
// Multiple drivers on cross-subsystem passthrough outputs — the
// `system_*` passthrough target shares its output wires with the
// cpu_0 external port driver on subsystem modules, which is the
// intended pattern (one master at a time via the internal mux).
// DROPPED (sign-off rule, never waivable): -nocheck MLTDRV
//=============================================================================
// Full-chiplet lint pass, 2026-08-09.
// Added while driving the AUTHORED findings of the nanosoc-multicore-system
// area to zero (verif/lint/full/). Every rule below was opened in the RTL
// before being waived, and the evidence is recorded with it. Where a finding
// turned out to be real it was FIXED instead and does not appear here.
// THE RULE FOR ADDING TO THIS SECTION: the justification must be true of every
// instance the rule can report, not just of the ones you looked at. If it is
// only true of a naming convention or a specific file, it belongs in
// lint/hal_design_info.txt as a pattern, not here as a rule name. That
// distinction is the whole reason the blanket URDWIR waiver above was removed.
//=============================================================================
// -- Deliberately open OUTPUT ports -------------------------------------
// UNCONN is the output-side counterpart of UNCONO/UCOPNM, already waived
// above, and of Verilator's PINCONNECTEMPTY-on-outputs, already waived in
// verif/lint/full. Every message in this class reads "Output port 'X' defined
// in design-unit 'Y' is not connected in its instance 'Z'": an unbound output
// drives nothing and can lose nothing. 102 instances in this area, all of the
// same shape -- unused cmsdk_apb_slave_mux PSEL2..15 on partially populated
// APB muxes, cmsdk_apb_uart TX/RX interrupt and BAUDTICK taps, cmsdk_ahb_to_apb
// APBACTIVE/PSTRB/PPROT, Ssp interrupt outputs, dma250 per-channel status, and
// the Cortex-M0+ integration sideband.
//   NOT waived, and must never be: UNCONI (unconnected INPUT), which is a
//   floating input and is on hal_report.py's NEVER_WAIVE list. The direction
//   split is the point -- do not collapse the two.
-nocheck UNCONN
// -- Informational notes, not findings ----------------------------------
// FSMIDN is severity *N: "FSM for state register 'x' has been recognized".
// It reports that HAL's FSM extractor worked. 14 instances, all correct
// recognitions of real state machines.
-nocheck FSMIDN
// TSKAWS: "Task 'ADP_txchar_next' used in always block" -- also *N, and the
// construct is legal and intended (see TSETGV below for the same file).
-nocheck TSKAWS
// -- Structural/hierarchy style -----------------------------------------
// FFNMOD asks for each flop group to sit in its own level of hierarchy. That
// is a house-style preference of the rule, not a property of the hardware; all
// 16 instances are ordinary output registers in qspi_controller. Adding
// hierarchy to satisfy it would obstruct the synthesis flow, not help it.
-nocheck FFNMOD
// REDOPR flags a reduction operator over a wide expression. Every instance in
// this area is the tie-off sink idiom used to declare intentionally-undecoded
// AMBA qualifiers -- `wire _unused = &{1'b0, HSIZE, HBURST, HPROT, ...};`.
// The reduction exists precisely so those bits count as read; flagging its
// width is flagging the idiom itself.
-nocheck REDOPR
// CASEZU: casez in bus_fault_monitor's fault decode. Deliberate -- the decode
// matches don't-care patterns and the file documents the encoding. (CASEX,
// the dangerous one, is not used and is not waived.)
-nocheck CASEZU
// MEMSIZ: "Memory declaration for 'hold_hwrite' defines a single-bit memory
// word." A 1-bit-wide array is exactly what a per-slot HWRITE hold buffer is.
-nocheck MEMSIZ
// BITUSD: reg_baud_div appears in a sensitivity list but not all its bits are
// used in the block. Harmless over-listing in the CMSDK-derived USRT; an
// always @(*) would compute the same sensitivity anyway.
-nocheck BITUSD
// IFSMCD: "Condition 'X' is present in all the branches of if/if-else." A
// common qualifier (QSPI_enable_sync, PREADY, PCLKEN) hoisted per-branch
// rather than wrapped. Same logic, different spelling.
-nocheck IFSMCD
// -- Parameterised / configuration folding -------------------------------
// CONSTC: "Constant conditional expression." 22 instances, all `if (PARAM)`
// or `if (WIDTH > n)` build-time configuration folding -- slcorem0p feature
// selects, wb_to_ahb3lite/rmii_to_mii width guards, the ahb_perf_probe
// enables, cmsdk_ahb_to_apb_ipc's PCLKEN folding. Synthesis resolves each at
// elaboration; that is the intent, and a design without configuration
// parameters is the only way to make the rule quiet.
-nocheck CONSTC
// USEPAR: parameter declared and not used. The two that were REAL --
// qspi_flash_ahb's FLASH_ADDR_W / CACHE_SIZE, which the SoC top passed into a
// wrapper with no destination -- have been dealt with in the RTL and the YAML
// (they are now documented as declarations, not configuration, and are read).
// What remains is genuinely benign: interface-compatibility parameters kept so
// a module can be swapped for its sibling without editing the instantiation
// (slcorem0p INCLUDE_JTAG, nanosoc_region_imem MEM_FPGA_IMG), and named
// constants kept for readability next to the ones that are used
// (cmsdk_ahb_to_apb_ipc ST_ILLEGAL, ctrl_ahb_perf_probe_regs CTRL_SNAP/
// CTRL_CLR document the CTRL bit encoding the write path decodes by position).
-nocheck USEPAR
// SHFTNC: "Shift by non-constant." Two instances, both a barrel shift by a
// small decoded field (eth_crc_checker byte lane, socdebug_adp_control nibble
// position). A variable shift is the operation, not an accident.
-nocheck SHFTNC
// LARMEM: "Large memory 'mem' exceeds the limit." Both instances are
// mis-scaled by the rule, which reports BITS x WIDTH rather than words:
//   dma250_ctx_ahb5_sram 'mem'   reported 32768 = 32 words x 32 b x 32
//                                actual 32 words x 32 b = 1024 flops (~0.3%
//                                of core area; 1024 SDFQD0 cells in the
//                                shipped gate netlist confirm it)
//   etc_capture 'fifo_sec'       reported 36864 = 8 ch x 2 slots x 48 b x ...
// Neither is a 32k-word RAM. Both are intended flop arrays.
-nocheck LARMEM
// UASREG: "Local register variable 'mem[n]' is unassigned, but is read at
// least once." All 32 instances are the DMA-250 context RAM
// (dma250_ctx_ahb5_sram). It is an unreset 32-word scratch that the DMA-250
// always WRITES a channel's context before it READS it -- that is the
// controller's own protocol, not an assumption. Resetting it would cost 1024
// flops' worth of reset routing for no functional gain. See the comment added
// at the declaration.
-nocheck UASREG
// -- Bit-wise vs logical operators, verified ------------------------------
// LOGORP: "Bit-wise OR in a conditional expression. Logical OR may have been
// intended." For 1-BIT operands `|` and `||` are identical, so this only
// matters if an operand is wider. Every operand at all 12 sites was checked
// against its declaration and is 1 bit:
//   socdebug_usrt_control  rx_overrun, tx_overrun, write_enable04/0c/10,
//                          baud_updated, reload_i, reload_f, baud_div_en,
//                          reg_baud_tick (all `wire`/`reg` with no range),
//                          intr_stat_set[n] / intr_stat_clear[n] (bit selects)
//   bus_fault_monitor      fault_seen_q, stat_clr
//   cmsdk_ahb_to_apb_ipc   sample_wdata_set, sample_wdata_clr
// If a wider operand is ever introduced this waiver stops being true -- which
// is why the widths are written down here rather than asserted in general.
-nocheck LOGORP
// -- Implicit signed/unsigned conversion ----------------------------------
// IMPDTC / TRUNCZ / IMPTYP / INTTOB / IPSFOU / IPUFSE / MXUANS.
// One family: an unsized decimal literal (`0`, `1`) or an unsigned
// concatenation meeting a sized or signed target. Verilog gives every one of
// these a defined result -- an unsized `0` takes the target's width, a
// concatenation is unsigned by definition -- so the conversion is well-formed,
// and TRUNCZ says so in its own message ("without a loss of bits").
// SCOPE LIMIT, read before assuming this covers a sign bug: these rules fire
// on the SPELLING, not on the arithmetic. They cannot tell a correct
// unsigned-concatenation subtract from an incorrect one. The known real
// arithmetic defects in this area (ha1588_servo's phase-step branch condition
// and its unclamped frequency accumulator) were found by reading the code, and
// they are NOT in these classes -- do not read a quiet report as evidence that
// signed arithmetic is right.
-nocheck IMPDTC
-nocheck TRUNCZ
-nocheck IMPTYP
-nocheck INTTOB
-nocheck IPSFOU
-nocheck IPUFSE
-nocheck MXUANS
// UELOPR: unequal-length operands in a BIT/ARITHMETIC operator (+, -). Unlike
// the relational family below, the result width here is the assignment
// target's, so a short operand is zero-extended into a defined result -- the
// classic `counter + 1`. All 6 sites are increments or decrements by an
// unsized literal.
//   DELIBERATELY NOT WAIVED: ULRELE and ULCMPE, the RELATIONAL and EQUALITY
//   counterparts, where padding really can change the answer. Those were
//   FIXED, one site at a time, by widening the narrow operand -- never by
//   sizing a parameter down. See hostio4_controller_fsm, dma250_lpi_onctrl,
//   ctrl_ahb_perf_probe_regs, etc_capture, eth_rx_cksum.
-nocheck UELOPR
// -- Array indexing, bounded by an explicit guard --------------------------
// POOBID / INDXOP on ethernet-subsystem-ahb/src/rtl/perf_probe/
// ahb_perf_probe_regs.v. The module reads six flattened counter buses with
// `bus[bank_raw*CW +: CW]`. HAL is arithmetically right that the expression is
// unbounded in isolation: bank_raw is 6 bits, so bank_raw*CW reaches 2016 on a
// 96-bit vector.
// It is bounded in fact, by line 122:
//     wire bank_valid = ~is_global & (bank_raw < N_PROBES[5:0]);
// and every part-select sits inside `if (bank_valid)`. With N_PROBES=3, CW=32
// (eth_ss_perf_probe_harness.sv, the only instantiation) bank_raw is 0..2, so
// the base is 0/32/64 and the widest select is [95:64] -- exactly the declared
// [95:0], no gap and no overrun. The underflow-wrap cases (bank_raw 62/63) can
// only arise when the word address is below the bank base, which `~is_global`
// masks independently. An out-of-range bank read returns 0, and a cocotb test
// for that read is the cheap way to keep it true.
//   INDXOP additionally objects to the multiply itself. A `base +: width`
//   select of a flattened bus REQUIRES a multiply; there is no other spelling.
//   The sibling ctrl_ahb_perf_probe_regs.v avoids both codes only because it
//   uses an unpacked array and an elaboration-bounded for-loop -- equally safe
//   at runtime, merely provable to a linter.
-nocheck POOBID
-nocheck INDXOP
// -- Tasks assigning module-level variables -------------------------------
// TSETGV: "Task 'X' assigns a value to global variable 'Y'." 13 instances,
// all five tasks in socdebug_adp_control.v (ADP_LINEACK_next,
// ADP_BUSWRITEINC_next, ADP_BUSREADINC_next, ADP_hexdigit_next,
// ADP_txchar_next). The concern the rule exists to raise is a second driver.
// Checked, not assumed: every call site of all five tasks lies inside the
// SINGLE `always @(posedge HCLK or negedge HRESETn)` block that begins at
// line 431 -- call sites at 488, 566, 574, 598, 604, 611, 614, 627, 632, 648,
// 652, 658, 671-741, all > 431, and the only other always block in the file
// (line 367) calls none of them. One procedural block, one driver. The tasks
// are next-state helpers factored out of a large FSM, which is what they read
// as.
//   Re-verify this if a second always block is ever added to that file --
//   MLTDRV is the rule that would catch the mistake, and it is NOT waived at
//   integration level.
-nocheck TSETGV

// ===== from tidelink/lint/hal.tcl  (8 rule(s))
// HAL rule configuration for TideLink lint flow
// Waive rules that conflict with AHB/AMBA/APB naming conventions or are
// style-only and not relevant to design correctness.
// -----------------------------------------------------------------------------
// HOW A WAIVER GETS HERE (read before adding one)
// Every entry is a claim that the rule cannot find a real defect in THIS block.
// A finding is fixed in the RTL unless fixing it would (a) change behaviour for
// a style rule, (b) require narrowing a wide operand, or (c) mean rewriting
// code that mitigates a known silicon issue. Where a class was only PARTLY
// unfixable the fixable instances were fixed first and the waiver records what
// is left, by site.
// This file is a UNIT-level ruleset. The full-chiplet lint
// (verif/lint/full/hal_rules.tcl) is a curated MERGE of the unit rulesets and
// deliberately drops rules it considers sign-off classes -- so adding a rule
// here does NOT silence it in the integration report. Anything added below
// that the merge currently drops is called out explicitly.
// -----------------------------------------------------------------------------
// ── Naming convention waivers ─────────────────────────────────────
// AHB/APB signal names (hclk, hresetn, hsel, apbs_psel, etc.) are
// defined by the AMBA spec and cannot follow HAL's default suffixes.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): INPTNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): OUTPNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CLKSNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): RSTNAM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MODLNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): RGOPNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): IDLENG
// Uppercase variable names — CMSDK IP uses ALL-CAPS ports (HCLK, HADDR, etc.)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LCVARN
// ── Style waivers ─────────────────────────────────────────────────
// Numeric literals in port widths (e.g. [31:0]) are standard practice
// (already waived by nanosoc-multicore-system/lint/hal.tcl): STYVAL
// Line length — 120 chars is acceptable for modern editors
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MAXLEN
// Per-port and per-signal comments are overkill for clear code
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMIOP
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMDEC
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMEND
// Always-block comments — not required for well-structured code
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMBLK
// Parameter base/width — defaults are fine for simple integer params
// (already waived by nanosoc-multicore-system/lint/hal.tcl): PRMVAL
// (already waived by nanosoc-multicore-system/lint/hal.tcl): PRMBSE
// Compiler directives (`ifdef/`endif) — used in CMSDK IP, acceptable
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CDWARN
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMDIR
// Block labels — meaningful code structure over mandatory labelling
// (already waived by nanosoc-multicore-system/lint/hal.tcl): NOBLKN
// Missing begin/end in single-statement if/always — acceptable style
// (already waived by nanosoc-multicore-system/lint/hal.tcl): NBGEND
// Empty default case statements — intentional no-op for completeness
// (already waived by nanosoc-multicore-system/lint/hal.tcl): EMPSTM
// Small integer literals (e.g. +2 for header overhead) in arithmetic — idiomatic SV
-nocheck CONSBS
// Expressions in port connections (e.g. zero-extend {2'b0, hwdata[31:20]}) —
// intentional boundary width coercions between 32-bit AHB and narrower internal buses
-nocheck EXPIPC
// Bit-select on unsigned — same set of boundary lines as EXPIPC
-nocheck BITUNS
// Function naming — repo does not use a func_ prefix convention
-nocheck FUNCNM
// Coded default case (empty default: ;) — intentional no-op when default
// assignment precedes the case statement; fully covered case is correct SV
-nocheck CDEFCV
// AMBA-mandated combinational input -> output paths. The structural equivalents
// CBPAHI/TPOUNR/SYNPRT/FDTHRU are already waived as design correctness items;
// IOCOMB is the same class (e.g. APB pready/pslverr or AHB hready combinational
// fan-out) and was the dominant noise source in the May/post-consolidation HAL
// runs (~110 of ~140 warnings). Waive to surface the genuine findings.
-nocheck IOCOMB
// Numeric suffix in identifiers (e.g. pending_0, interrupt_1) — by design
// (already waived by nanosoc-multicore-system/lint/hal.tcl): NUMSUF
// Separate line for each signal declaration — acceptable grouping
// (already waived by nanosoc-multicore-system/lint/hal.tcl): SEPLIN
// ── Structural waivers ───────────────────────────────────────────
// Tied outputs are by design:
//   - hreadyout=1, hresp=0 (zero-wait-state AHB slave)
//   - apbs_pready=1, apbs_pslverr=0 (zero-wait-state APB slave)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TIELOG
// Feedthrough paths are intentional:
//   - hwdata→reg_wdata, reg_rdata→hrdata (AHB-to-reg bridge)
//   - haddr→translated_haddr (address translation)
//   - apbs_pwdata→accumulator, accumulator→apbs_prdata (APB regs)
// 2026-08-09 re-justification (14 findings). Every one is a combinational
// path a protocol or a datapath REQUIRES; "fixing" any of them means adding a
// register stage, which is a behaviour change, not a lint fix:
//   tidelink_apb_regs   x10  paddr[4:2]/pwdata -> the per-region reg_addr /
//                            reg_wdata fan-out, and current_credit_count ->
//                            credit_count_data. This is an APB address/data
//                            decode; registering it breaks the zero-wait-state
//                            slave contract (apbs_pready tied 1).
//   tidelink_fifo_ctrl:198   addr -> translated_addr. Address translation is
//                            combinational by definition.
//   tl_addr_trans_cam:59     addr_i[23:0] -> addr_o[23:0]. The CAM replaces
//                            only addr[31:24]; the low 24 bits pass through by
//                            design (see the comment at that line).
//   tidelink_idelay_rx:226   pad_rx_i -> pad_rx_o in the USE_IDELAY=0 arm.
//                            That arm IS the documented bit-exact passthrough.
//   tidelink_rxclk_buf:87    clk_i -> clk_o. A clock buffer. Registering a
//                            clock is not a thing.
// NOTE: verif/lint/full/hal_rules.tcl currently DROPS this rule from the merge
// ("sign-off rule"), so these 14 still appear in the integration report. The
// loading concern FDTHRU exists to raise is a physical one and belongs to
// timing/SI closure, not to RTL lint; the RTL question is settled above.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): FDTHRU
// Mixed sync/async is expected with async active-low reset (hresetn)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): SYNASN
// Combinational paths crossing hierarchy — expected in a hierarchical
// design where combinational logic feeds registered logic across module
// boundaries (e.g. fifo_ctrl ↔ ahb_to_sram ↔ sram)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CBPAHI
// Combinational outputs at top level — AHB/APB protocols are comb by design
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TPOUNR
// Combinational (async) output ports — same reason
// (already waived by nanosoc-multicore-system/lint/hal.tcl): SYNPRT
// Large operand arithmetic — inherent to parameterised widths
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LRGOPR
// Potential overflow — intentional wrapping for circular FIFO pointers
// (already waived by nanosoc-multicore-system/lint/hal.tcl): POIASG
// Multiple non-blocking assigns — set/clear pattern for pending regs
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MULNBA
// Parameters in port expressions — localparam addresses passed to returner
// (already waived by nanosoc-multicore-system/lint/hal.tcl): PRMEXP
// (already waived by nanosoc-multicore-system/lint/hal.tcl): IPRTEX
// FSM modelling style — HAL expects specific patterns, ours is valid
// (already waived by nanosoc-multicore-system/lint/hal.tcl): BADFSM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): EXTFSM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TRNMBT
// (already waived by nanosoc-multicore-system/lint/hal.tcl): STMCNM
// Typedef not in package — module-local typedefs are acceptable
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TDOPKG
// Lowercase type names — SV convention for types
// 2026-08-09 re-justification (7 findings: state_t, puf_state_t, rx_state_t,
// tx_state_t, hw_sync_state_t, gm_state_t, sub_state_t). UCCONN is RMM §5.2.1,
// a pure NAMING rule of Warning severity — "use upper case for names of
// constants and user-defined types". The `lower_case_t` suffix is the
// SystemVerilog convention, is used consistently across this repo and its
// dependencies, and renaming a typedef changes nothing but the identifier.
// This is the same category as ALOWID / BLKLNM / SIGLEN / TASKNM / VLFLNM,
// which verif/lint/full/hal_report.py already classifies as STYLE and
// suppresses. UCCONN's absence from that list looks like an omission rather
// than a decision, and it is NOT in that file's NEVER_WAIVE set either.
// Recommendation to the integrator: add UCCONN to hal_report.py:STYLE_RULES
// rather than re-adding it to the merged ruleset. The source should not be
// de-idiomatised to satisfy a naming rule the project has consciously rejected.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): UCCONN
// Clock/reset renamed across CMSDK hierarchy (hclk→HCLK, hresetn→HRESETn)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DIFCLK
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DIFRST
// Aliased wires — read/write target share same expression by design
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DALIAS
// FF with constant data — reset_n_d1 tied to 1'b1 for deassertion detection
// (already waived by nanosoc-multicore-system/lint/hal.tcl): FFCSTD
// FF without synchronous reset — async reset is sufficient
// (already waived by nanosoc-multicore-system/lint/hal.tcl): FFWNSR
// Mixed driver types on vector — token_count_r init vs runtime, harmless
// 2026-08-09 re-justification (9 findings). DFDRVS is NOT a multi-driver rule
// — that is MLTDRV, which this file does not waive, which the integration
// gates, and which reports ZERO across the whole chiplet. So every bit here
// still has exactly one driver; DFDRVS is reporting that different SUB-RANGES
// of a vector are driven by different constructs. The instances are:
//   apb_regs:217 release_threshold, fifo_ctrl:122 credit_count_r,
//   perf:333 trend_r, ptp:364 hw_sync_interval_r,
//   ptp_servo:133-135 servo_kp_r/ki_r/step_thresh_r
//     — a reset constant vs. a register-write value, in one always_ff.
//   tidelink_top:575/601 s_axi_awaddr / s_axi_araddr
//     — [31:0] from the XHB500 bridge instance, [35:32] tied to 4'h0 for the
//       unused top of the 36-bit AXI address (see the comment at :569).
// The AXI pair sits on the AW/AR channels, which carry a known silicon issue
// (TL-009 a2l CDC self-latch). Collapsing them into a single concatenated
// driver would be a pure renaming, but it is a renaming of the exact nets
// under investigation, so it is deliberately NOT done for a style finding.
// NOTE: dropped from verif/lint/full/hal_rules.tcl's merge as a "sign-off
// rule"; the argument above is why that classification does not fit DFDRVS.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DFDRVS
// Unused port bits — AHB htrans[0], hresp/hrdata on write-only master,
// APB paddr upper/lower bits only [5:2] decoded. All by protocol/design.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): USEPRT
// Unconnected output naming — debug signals don't need _nc suffix
// (already waived by nanosoc-multicore-system/lint/hal.tcl): UCOPNM
// Unconnected output ports — debug signals for cocotb probing only
// (already waived by nanosoc-multicore-system/lint/hal.tcl): UNCONO
// Unread local registers — debug signal aliases for testbench visibility
// (already waived by nanosoc-multicore-system/lint/hal.tcl): URDREG
// Glue logic at top level — expected for address derivation wires
// (already waived by nanosoc-multicore-system/lint/hal.tcl): ATLGLC
// ── 2026-08-09 waivers (full-chiplet HAL pass) ───────────────────────────
// Added while driving TideLink's authored HAL findings to zero. 48 of the 138
// were FIXED in the RTL (widths, signedness, dead localparams, the PTP servo
// lock compare); these are the classes where a fix would have been worse than
// the finding. Counts are the authored TideLink instances at the time.
// UNCONN (33) — "<direction> port 'x' ... is not connected in its instance".
// ALL 33 authored instances are OUTPUT ports, deliberately left open:
//   xhb500_ahb_to_axi_bridge_chiplet_slv (15) and
//   xhb500_axi_to_ahb_bridge_chiplet_mst (14) — AXI5/ACE-Lite sidebands
//     (awdomain/awregion/awnsaid/hexokay/hnonsec/hqos/hwstrb/...) and the
//     Q-Channel low-power handshakes (clk_/pwr_qactive/qacceptn/qdeny). This
//     integration drives no Q-Channel and no AXI5 sideband; the vendor IP
//     emits them unconditionally.
//   tidelink_gpio_phy_apb_regs.noise_mode_o, axi_chiplet_controller.sb_wake /
//   generalbus_out, tidelink_addr_translator.chp1_ahb_haddr_o (NUM_CHANNELS=1)
//     — debug/optional taps with no consumer in this configuration.
// DIRECTION IS THE WHOLE ARGUMENT, and the detector for the other direction
// survives this waiver twice over:
//   * HAL UNCONI (unconnected INPUT, severity ERROR) is NOT waived here and is
//     in hal_report.py's NEVER_WAIVE set.
//   * Verilator's PINMISSING/PINCONNECTEMPTY run over the SAME filelist in the
//     same pass and are direction-gated in verilator_lint.py: outputs waived,
//     inputs and unresolved-direction pins GATED. That pass is what caught the
//     real tidelink_fifo_ahb floating-input pair, and it fires whether or not
//     the port is read inside the instantiated module — the one case UNCONI
//     could miss.
// Do NOT extend this to UNCONI.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): UNCONN
// FSMIDN (7) — severity NOTE, not a warning: "FSM for state register 'x' has
// been recognized". It is HAL telling you its FSM extraction worked. There is
// nothing to fix and nothing to review; suppressing it stops 7 informational
// lines from being counted as design findings.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): FSMIDN
// TRGGLT (1, severity NOTE) — tl_addr_trans_cam:89, the `found` early-exit
// flag in the priority encoder. Single procedural driver, one always @(*),
// and the final value is stable within the block, so this is not the
// multi-driver/fc_shell-blocking class. The ascending-loop-with-flag form is
// a DELIBERATE QoR choice (documented at that line: it synthesises as a
// parallel priority tree rather than a cascading mux chain), and this design
// is already in P&R — restructuring it for a note is not a trade worth making.
-nocheck TRGGLT
// CONSTC (4) — constant conditional expression. All four are compile-time
// configuration folding, which is what parameters are for:
//   tidelink_addr_translator:97  if (NUM_CHANNELS > 1)   [instantiated with 1]
//   tidelink_ptp:372             PHC_LOCK_GATE_EN == 0   [0 in the shipped cfg]
//   tidelink_top:1017            configuration select
//   tidelink_top:2129            the STUB_PTP/STUB_SERVO elaboration guard
// The dead branch is the POINT: the arm not taken must not be synthesised.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CONSTC
// BADSYS (1) — tidelink_top:2130, `$error` inside an `initial` block that
// checks an illegal STUB_PTP/STUB_SERVO combination at elaboration. HAL is
// reporting that synthesis ignores the system task, which is correct AND
// intended: the guard exists to stop a bad parameterisation reaching a
// simulator or an elaborator, and it must not emit hardware.
-nocheck BADSYS
// REDOPR (3) — wide reduction OR. All three are the standard
// "reference-a-signal-so-it-is-not-reported-unused" idiom, feeding a wire with
// no consumer, which synthesis removes entirely — so the "complex logic"
// REDOPR warns about is never built:
//   tidelink_idelay_rx:230  (|phase_tap_i) in the USE_IDELAY=0 passthrough arm
//   tidelink_top:1204       |{eye_force_phase_en/val, eye_force_slip_val}
//   tidelink_top:1334       |{lane_mismatch_pulse, lane_dwell_min_dist}
// (already waived by nanosoc-multicore-system/lint/hal.tcl): REDOPR
// LOGORP (1) — tidelink_top:1890, `(s_axi_bvalid_ctrl | synth_b_pending) ?`.
// Both operands verified 1-bit, so `|` and `||` are identical in hardware.
// This line is inside the TL-009 synthetic-B / corrupted-BID mitigation for a
// KNOWN SILICON WEDGE on the AW/W/B channels. `|` and `||` differ on X in
// simulation (`||` can resolve X|1 to 1). Perturbing a wedge mitigation's
// X-behaviour to satisfy a style rule is not a trade this design can afford.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LOGORP
// USEPAR (5 residual; 7 genuinely-dead localparams were DELETED instead —
// HTRANS_IDLE/HTRANS_NONSEQ/HSIZE_WORD in tidelink_fc_adapter, HTRANS_IDLE/
// HTRANS_NONSEQ in tidelink_ptp, NS_PER_SECOND and MBOX_SUB_NS_OFFSET in
// tidelink_ptp_servo). What is left is not dead code:
//   tidelink_idelay_rx:96  IDELAY_GRP  — documentary BY DESIGN. Vivado rejects
//     a string-typed parameter in an (* IODELAY_GROUP *) attribute, so the
//     attribute uses a literal; the parameter records the value that literal
//     and the XDC must agree on. Deleting it deletes the contract.
//   tidelink_idelay_rx:106 REFCLK_MHZ  — used at IDELAYE2.REFCLK_FREQUENCY,
//     inside the USE_IDELAY=1 arm that the ASIC parameterisation prunes.
//   tidelink_top:94  USE_PHY_V2        — used at `if (USE_PHY_V2)`, whose
//     false arm (the only one built today) elaborates empty.
//   tidelink_top:1024 TXGEN_CGD_EFF    — used at u_tx_gen.CREDIT_GATE_DIS
//     inside `if (TXGEN_PRESENT)`.
//   tidelink_perf:34 FC_DATA_W         — an interface-width parameter every
//     instantiator passes; removing it would break those instantiations for a
//     style finding.
// The last four are "unused only in the configuration HAL elaborated", which
// is a statement about the parameterisation, not about the code.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): USEPAR
// MXUANS (5 residual) — expression with both signed and unsigned operands.
// The 5 fixable instances WERE fixed (tidelink_mul_iter:70 and the
// raw_offset_r/raw_delay_r sign-extensions in tidelink_ptp_servo now use a
// size cast, which preserves signedness, instead of a hand-written sign bit
// inside a concatenation). The residue is in the PI servo, where mixing is
// deliberate and the mix is what makes the arithmetic correct:
//   ptp_servo:586  needs_phase_step_r || (offset_r >  $signed(thresh)) ||
//                                        (offset_r < -$signed(thresh))
//     — a 1-bit unsigned flag OR-ed with two signed comparisons. `||` operands
//       are self-determined booleans; there is no width or sign interaction.
//   ptp_servo:599/602  the anti-windup guards, which test integral_r[31] /
//     offset_r[31] (unsigned bit-selects) alongside a signed add.
//   ptp_servo:632/634  current_frac_r - (pi_p_term_r + mul_result[63:32]).
//     current_frac_r is the unsigned Q0.32 frequency word; per LRM 11.8.1 one
//     unsigned operand makes the whole expression unsigned, which is exactly
//     the 32-bit wrapping arithmetic a frequency accumulator needs.
// These are correct as written and are covered by cocotb/tidelink_ptp_servo
// (SRV-006 anti-windup, SRV-012 PI reference). Rewriting live PI arithmetic on
// a tapeout branch to remove a signedness annotation is not worth the risk.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MXUANS
// CMSDK-specific warnings that leak through
// (already waived by nanosoc-multicore-system/lint/hal.tcl): OLDALW
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LOGNEG
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LOGAND
// (already waived by nanosoc-multicore-system/lint/hal.tcl): BOUINC
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MEMRNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MICAWS
// (already waived by nanosoc-multicore-system/lint/hal.tcl): BBXSIG

// ===== from tidechart/lint/hal.tcl  (1 rule(s))
// TideChart HAL Lint Waivers
// Cadence HAL (Xcelium) rule configuration for the TideChart unit lint flow
// (`tidechart/lint/Makefile`) and, by union, for the full-chiplet pass in
// `verif/lint/full/` (see that README: `hal_rules.tcl` is the merge of every
// unit-level `lint/hal.tcl` in the integration).
// -----------------------------------------------------------------------------
// SIGN-OFF INVARIANT
// Nothing in this file may waive a sign-off rule. The classes that must stay
// live in authored RTL are, at minimum:
//   MLTDRV  CLKDMN  INSYNC  GLTASR  UNCONI  SIZMIS
//   ULRELE  ULCMPE                       (padding produces an incorrect result)
//   any *E in authored RTL
//   any empty-or-omitted pin on an input or inout
// ULRELE and ULCMPE are the reason: they are the only width classes that assert
// a WRONG RESULT rather than a style deviation, and TideLink's own README ties
// the class to a real silicon finding. Every ULRELE/ULCMPE site in TideChart was
// FIXED (2026-08-09), not waived -- always by widening the narrow operand, never
// by narrowing the wide one. If one reappears, it is a new defect.
// Every waiver below records WHY. A waiver without a justification is a bug you
// have agreed to keep. If the justification stops being true, delete the line.
// -----------------------------------------------------------------------------
// Contributors
//   David Mapstone (d.a.mapstone@soton.ac.uk)
// Copyright 2026, SoC Labs (www.soclabs.org)
// -- Pre-existing STARC waivers, PARKED --------------------------------------
// This file is consumed by `hal -file`, which is HAL's command-file syntax --
// `//` comments and `-nocheck <RULE>` directives -- and that is the form every
// other unit ruleset in the integration uses (tidelink, ethernet-mac-ahb,
// nanosoc-multicore-system, ...). The two lines below were written in Tcl
// `hal::rule_waive` form, which is why `verif/lint/full/hal_rules.tcl` records
// TideChart as "(rule_waive form, see below)" and folded neither of them into
// the merged ruleset: they have never reached the integration pass.
// They are parked rather than deleted -- they name STARC ruleset entries, not
// HAL rule codes, and the unit Makefile runs `-check ALL_RTL`, not STARC, so
// they are no-ops there too. Restore them (in whichever form the STARC flow
// wants) if STARC checking is ever turned on; do not leave them live in a
// command file that HAL parses positionally.
//   hal::rule_waive -rulename STARC05-2.1.3.1 \
//       -comment "Parameterized port arrays for multi-port design"
//   hal::rule_waive -rulename STARC-2.6.1.1 \
//       -comment "LFSR feedback taps in election FSM"
// ==========================================================================
// Width / arithmetic classes
// ==========================================================================
// UELOPR -- unequal-length operand in a bit/arithmetic operator.
// Every remaining instance in TideChart is the same shape: a register that is
// ID_W (5) or PORT_W (3) bits wide, minus an UNSIZED literal 1, feeding an
// array index -- e.g. `root_hop_count_arr[hop_target_r - 1]`,
// `route_table[read_addr - 1]`. The literal makes the subtraction 32-bit, so
// index 0 underflows to 32'hFFFFFFFF, which every reader guards with an
// explicit `(addr == 0) ? <const> : table[addr-1]` ternary.
// "Fixing" this by doing the arithmetic at the index width is the WRONG
// direction and would manufacture a bug: 5'd0 - 5'd1 is 5'd31, an IN-RANGE
// entry of a 31-entry table, so the underflow would stop being harmless and
// start aliasing onto a real route. The alternative -- zero-extending each
// register to 32 bits -- is 20+ edits across a peer-facing FSM that changes no
// behaviour and no netlist. Neither is worth it; the class is not the
// wrong-result class (that is ULRELE, which is fixed above).
// (already waived by nanosoc-multicore-system/lint/hal.tcl): UELOPR
// POOBID -- variable index/range selection potentially outside the range.
// HAL cannot bound a dynamic index through a guard, so it reports every
// guarded one. The surviving instances are:
//   tidechart_route_table.sv:108-124   `(addr == 0) ? const : table[addr-1]`
//                                      addr is ID_W bits, table has 31 entries,
//                                      so 1..31 -> 0..30, all in range.
//   tidechart_enum_fsm.sv (root_parent_id / root_hop_count_arr / root_egress /
//                          root_uplink_arr / link_active)
//                                      same `id-1` shape, same guards.
// The unguarded ones were real and are FIXED, not waived:
//   crossbar enum_fc_tx_port  -> bounds-checked (A5)
//   enum_fsm assign_port      -> bounds-checked
//   every scan pointer        -> indexed at $clog2(NUM_PORTS) width
// A POOBID on a NEWLY unguarded index is therefore still a finding worth
// having; this waiver keeps the class from burying it.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): POOBID
// MXUANS -- expression mixes signed and unsigned operands.
// The only instances are `for (pi = 0; pi < NUM_CHIPLETS_MAX; ...)` integer
// loop variables compared against unsigned registers. The loop bounds make pi
// provably non-negative. Fixed at the one site HAL also flagged ULRELE on;
// the residue is the loop-variable idiom itself.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MXUANS
// ==========================================================================
// Structural / declaration classes
// ==========================================================================
// USEPAR -- parameter declared and unused.
// TideChart's sub-modules are instantiated with ONE uniform parameter list
// from tidechart_controller.sv so that a configuration change is a single
// edit at the top. Removing FC_DATA_W / PUF_ENABLE / ACCEL_COUNT /
// SRAM_BLOCK_COUNT / PUF_NUM_WORDS / RST_WAIT_RT_ACK / PAYLOAD_W from the
// modules that do not currently read them would break those instantiations and
// re-break them the next time a phase starts using one. Note this is NOT the
// same as the "dead configuration knob" class (plan B6, qspi_flash_ahb): these
// parameters are consumed by siblings in the same instantiation.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): USEPAR
// DFDRVS -- sub-parts of a vector driven by different assignment types.
// Register banks where the reset branch writes the whole vector and the APB
// write branch writes named bit fields (timeout_reg_r, cong_bcast_period_r,
// cong_jitter_mask_r, lfsr_r, free_counter_r, own_class_r). Single procedural
// driver in every case -- confirmed by MLTDRV = 0 across the chiplet -- so this
// is a description-style note, not a multi-driver.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DFDRVS
// MEMSIZ -- memory declaration with a single-bit word.
// `secure_table` / `valid_table` (tidechart_route_table.sv) and `seen_valid_r`
// (tidechart_link_state_agent.sv) are deliberately one flag per entry, sized by
// the same NUM_ENTRIES as the tables they qualify. HAL's "check for an error in
// the register declaration" is the right question and the answer is no.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MEMSIZ
// LARMEM -- large memory note.
// HAL's LARMEM figure is bits x width, not words (see
// docs/LINT_REMEDIATION_PLAN.md §0, where the same class was misread as a 1 Mib
// DMA context RAM and was actually 1 024 flops). root_port_subtree_r and
// root_below_r are NUM_CHIPLETS_MAX x NUM_CHIPLETS_MAX bit masks. This is a
// note (*N), not a warning, and the area is accounted for in the netlist.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LARMEM
// NAUTOF is NOT waived -- all four static functions were given `automatic`
// (2026-08-09), matching tidechart_link_state_agent.sv, which already did.
// ==========================================================================
// Intentional-structure classes
// ==========================================================================
// FDTHRU -- combinational feedthrough from an input to an output.
// tidechart_crossbar is a crossbar: routing an input port's data to a selected
// output with no register in between is its entire function, and the AXI-Stream
// contract requires the ready/valid path to be combinational. The same applies
// to the link-state agent's bcast_rx_data[31:27] -> rt_hop_addr lookup tap.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): FDTHRU
// SHFTNC -- shift by a non-constant.
// The LFSR step, the FC path-field pack (`cur_port_idx_r << (hop*PORT_W)`) and
// the chiplet-bitmap builds (`1 << id`) are all variable shifts by
// construction. Shift amounts are bounded by the field widths they index.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): SHFTNC
// CONSTC -- constant conditional expression.
// `if (PUF_ENABLE)` / `if (NUM_PORTS > 1)` configuration folding. The shipping
// build sets PUF_ENABLE=0 and NUM_PORTS=1, so these fold at elaboration exactly
// as intended -- that is what a generate-time parameter is for.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CONSTC
// MULOPR is NOT waived -- the three `PUF_ENABLE &&` sites were rewritten as
// `(PUF_ENABLE != 0) &&` (2026-08-09), the form the same file already used.
// FUSEGV -- function reads a module-scope variable.
// tidechart_link_state_agent::build_packet reads link_active and
// local_link_state_i deliberately: it builds a broadcast packet FROM the
// module's current link state, and passing 2 x NUM_PORTS values in as arguments
// would obscure that without changing the logic. The function is `automatic`
// and combinational.
-nocheck FUSEGV
// IFSMCD -- the same condition appears in all branches of an if/else-if chain.
// One instance: the subtree write-port decode in tidechart_apb_regs.sv, where
// the chain is `port < NUM_PORTS` / `port == NUM_PORTS` / else, i.e. a
// three-way range decode written as a chain. HAL is pattern-matching the shared
// left-hand operand, not finding redundant logic.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): IFSMCD
// ==========================================================================
// Reviewed and deliberately NOT waived by rule -- recorded here so the next
// reader does not have to re-derive it
// ==========================================================================
// TERMST (*E) at tidechart_election_fsm.sv -- "FSM for state register 'state_r'
// has terminal states 4".
// This finding is FACTUALLY WRONG about this design and is left visible rather
// than waived, because it is an *E and the sign-off rule is that no *E in
// authored RTL gets silenced.
// ST_SETTLED (3'd4) does have an exit arc. It is in the SEQUENTIAL block:
//     always @(posedge clk or negedge resetn)
//         if (!resetn)      state_r <= ST_IDLE;
//         else if (restart) state_r <= ST_IDLE;   // I8 soft re-arm, TC_CTRL[3]
//         else              state_r <= state_next;
// HAL extracted the FSM from the combinational next-state function alone, where
// ST_SETTLED does self-loop, and never saw the restart override. The exit is
// reachable from firmware (TC_CTRL.RESET) and is exercised by the election
// cocotb environment.
// Moving `restart` into the next-state function would make HAL see the arc, and
// was REJECTED as a fix: `state_next` is also consumed at
// tidechart_election_fsm.sv:133 as the LFSR reseed trigger
// (`state_r == ST_WAIT_LINKS && state_next == ST_CLAIM_TX`). Folding restart
// into state_next would suppress that reseed on a restart that coincides with
// ST_WAIT_LINKS -- a real behaviour change, to satisfy a false positive.

// ===== from nanosoc-multicore-system/ethernet-subsystem-ahb/ethernet-mac-ahb/lint/hal.tcl  (7 rule(s))
// HAL rule configuration for Ethernet MAC AHB bridge lint flow
// Waive rules that conflict with AHB/AMBA/Wishbone naming conventions or are
// style-only and not relevant to design correctness.
// ── Naming convention waivers ─────────────────────────────────────
// AHB signal names (hclk, hresetn, hsel, htrans, etc.) and Wishbone
// signal names (wb_cyc, wb_stb, etc.) are defined by their respective
// specs and cannot follow HAL's default suffixes.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): INPTNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): OUTPNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CLKSNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): RSTNAM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MODLNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): RGOPNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): IDLENG
// Uppercase variable names — AHB signals use mixed case (sHADDR, mHTRANS)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LCVARN
// ── Style waivers ─────────────────────────────────────────────────
// Numeric literals in port widths (e.g. [31:0]) are standard practice
// (already waived by nanosoc-multicore-system/lint/hal.tcl): STYVAL
// Line length — 120 chars is acceptable for modern editors
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MAXLEN
// Per-port and per-signal comments are overkill for clear code
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMIOP
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMDEC
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMEND
// Always-block comments — not required for well-structured code
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMBLK
// Parameter base/width — defaults are fine for simple integer params
// (already waived by nanosoc-multicore-system/lint/hal.tcl): PRMVAL
// (already waived by nanosoc-multicore-system/lint/hal.tcl): PRMBSE
// Compiler directives (`ifdef/`endif) — used for ETH_WISHBONE_B3 etc.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CDWARN
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMDIR
// Block labels — meaningful code structure over mandatory labelling
// (already waived by nanosoc-multicore-system/lint/hal.tcl): NOBLKN
// Missing begin/end in single-statement if/always — acceptable style
// (already waived by nanosoc-multicore-system/lint/hal.tcl): NBGEND
// Empty default case statements — intentional no-op for completeness
// (already waived by nanosoc-multicore-system/lint/hal.tcl): EMPSTM
// Numeric suffix in identifiers — by design
// (already waived by nanosoc-multicore-system/lint/hal.tcl): NUMSUF
// Separate line for each signal declaration — acceptable grouping
// (already waived by nanosoc-multicore-system/lint/hal.tcl): SEPLIN
// ── Structural waivers ───────────────────────────────────────────
// Tied outputs are by design:
//   - mHREADYOUT=1 (bridge never inserts wait states)
//   - mHSIZE=3'b010, mHPROT=4'b0011 (fixed AHB transfer parameters)
//   - sHREADYOUT tied to ack (zero-wait-state AHB slave)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TIELOG
// Feedthrough paths are intentional:
//   - from_m_wb_dat_o→mHWDATA, mHRDATA→to_m_wb_dat_i (data pass-through)
//   - sHWDATA→to_wb_dat_i, from_wb_dat_o→sHRDATA (AHB-to-WB data path)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): FDTHRU
// Mixed sync/async is expected with async active-low reset (rst_n_i/hresetn)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): SYNASN
// Combinational paths crossing hierarchy — expected in a hierarchical
// design where bridges connect combinational outputs to registered logic
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CBPAHI
// Combinational outputs at top level — AHB/WB protocols are comb by design
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TPOUNR
// Combinational (async) output ports — same reason
// (already waived by nanosoc-multicore-system/lint/hal.tcl): SYNPRT
// Large operand arithmetic — inherent to address calculation
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LRGOPR
// Potential overflow — intentional wrapping for burst beat counters
// (already waived by nanosoc-multicore-system/lint/hal.tcl): POIASG
// Multiple non-blocking assigns — set/clear pattern
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MULNBA
// Parameters in port expressions
// (already waived by nanosoc-multicore-system/lint/hal.tcl): PRMEXP
// (already waived by nanosoc-multicore-system/lint/hal.tcl): IPRTEX
// FSM modelling style — HAL expects specific patterns, ours is valid
// (already waived by nanosoc-multicore-system/lint/hal.tcl): BADFSM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): EXTFSM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TRNMBT
// (already waived by nanosoc-multicore-system/lint/hal.tcl): STMCNM
// Typedef not in package — module-local typedefs are acceptable
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TDOPKG
// Lowercase type names
// (already waived by nanosoc-multicore-system/lint/hal.tcl): UCCONN
// Clock/reset renamed across hierarchy (clk_i→hclk, rst_n_i→hresetn)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DIFCLK
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DIFRST
// Aliased wires — bridge pass-through by design
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DALIAS
// FF with constant data — acceptable for control logic
// (already waived by nanosoc-multicore-system/lint/hal.tcl): FFCSTD
// FF without synchronous reset — async reset is sufficient
// (already waived by nanosoc-multicore-system/lint/hal.tcl): FFWNSR
// Mixed driver types
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DFDRVS
// Unused port bits — WB sel/bte unused in wb_to_ahb3lite (word-only transfers),
// AHB htrans[0] etc. Protocol-inherent unused bits.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): USEPRT
// Unconnected output naming — mHREADYOUT not connected at top level by design
// (already waived by nanosoc-multicore-system/lint/hal.tcl): UCOPNM
// Unconnected output ports
// (already waived by nanosoc-multicore-system/lint/hal.tcl): UNCONO
// Unread local registers
// (already waived by nanosoc-multicore-system/lint/hal.tcl): URDREG
// Glue logic at top level — expected for address/clock wiring
// (already waived by nanosoc-multicore-system/lint/hal.tcl): ATLGLC
// Combinational always-block outputs read via continuous assign — standard
// Verilog pattern for separating comb logic from output wiring
-nocheck REVROP
// Combinational input-to-output paths — bridges are pass-through by design
// (already waived by tidelink/lint/hal.tcl): IOCOMB
// Extraneous logic in FSM sequential block — address/burst latching is
// intentionally co-located with the state register for clarity
-nocheck EXTSEQ
// Clock signal drives data pin — inherent to RMII clock-divider design
// where phase counters are derived from the reference clock
-nocheck CDFDAT
// Clock does not drive data for some FFs — mrxerr is only reset, never
// toggled by data in the current design (RMII error not yet wired)
-nocheck CLKNED
// Empty begin/end block — third-party bridge (ahb3lite_to_wb submodule)
-nocheck EMPBLK
// Control character in source — third-party bridge
-nocheck CTLCHR
// Constant left-padded — width mismatch in third-party bridge
-nocheck PADMSB
// Old-style always blocks — Verilog-2001 style used in third-party bridges
// (already waived by nanosoc-multicore-system/lint/hal.tcl): OLDALW
// Logic operators on multi-bit operands
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LOGNEG
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LOGAND
// Bit-width mismatches — third-party IP style
// (already waived by nanosoc-multicore-system/lint/hal.tcl): BOUINC
// Memory naming
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MEMRNM
// Micro-architectural warnings
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MICAWS
// Black-boxed signal warnings
// (already waived by nanosoc-multicore-system/lint/hal.tcl): BBXSIG

// ===== from nanosoc-multicore-system/inter-processor-communications-ahb/lint/hal.tcl  (1 rule(s))
// HAL rule configuration for IPC Mailbox lint flow
// Waive rules that conflict with AHB/AMBA/APB naming conventions or are
// style-only and not relevant to design correctness.
// ── Naming convention waivers ─────────────────────────────────────
// AHB/APB signal names (hclk, hresetn, hsel, apbs_psel, etc.) are
// defined by the AMBA spec and cannot follow HAL's default suffixes.
// (already waived by nanosoc-multicore-system/lint/hal.tcl): INPTNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): OUTPNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CLKSNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): RSTNAM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MODLNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): RGOPNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): IDLENG
// Uppercase variable names — CMSDK IP uses ALL-CAPS ports (HCLK, HADDR, etc.)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LCVARN
// ── Style waivers ─────────────────────────────────────────────────
// Numeric literals in port widths (e.g. [31:0]) are standard practice
// (already waived by nanosoc-multicore-system/lint/hal.tcl): STYVAL
// Line length — 120 chars is acceptable for modern editors
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MAXLEN
// Per-port and per-signal comments are overkill for clear code
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMIOP
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMDEC
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMEND
// Always-block comments — not required for well-structured code
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMBLK
// Parameter base/width — defaults are fine for simple integer params
// (already waived by nanosoc-multicore-system/lint/hal.tcl): PRMVAL
// (already waived by nanosoc-multicore-system/lint/hal.tcl): PRMBSE
// Compiler directives — used in CMSDK IP, acceptable
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CDWARN
// (already waived by nanosoc-multicore-system/lint/hal.tcl): COMDIR
// Block labels — meaningful code structure over mandatory labelling
// (already waived by nanosoc-multicore-system/lint/hal.tcl): NOBLKN
// Missing begin/end in single-statement if/always — acceptable style
// (already waived by nanosoc-multicore-system/lint/hal.tcl): NBGEND
// Empty default case statements — intentional no-op for completeness
// (already waived by nanosoc-multicore-system/lint/hal.tcl): EMPSTM
// Numeric suffix in identifiers (e.g. slot0, slot1) — by design
// (already waived by nanosoc-multicore-system/lint/hal.tcl): NUMSUF
// Separate line for each signal declaration — acceptable grouping
// (already waived by nanosoc-multicore-system/lint/hal.tcl): SEPLIN
// ── Structural waivers ───────────────────────────────────────────
// Tied outputs are by design:
//   - ahbs_hreadyout=1, ahbs_hresp=0 (zero-wait-state AHB slave)
//   - pready=1, pslverr=0 (zero-wait-state APB slave)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TIELOG
// Feedthrough paths are intentional in register decode logic
// (already waived by nanosoc-multicore-system/lint/hal.tcl): FDTHRU
// Mixed sync/async is expected with async active-low reset (hresetn)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): SYNASN
// Combinational paths crossing hierarchy — register decode
// (already waived by nanosoc-multicore-system/lint/hal.tcl): CBPAHI
// Combinational outputs at top level — APB protocol is comb by design
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TPOUNR
// (already waived by nanosoc-multicore-system/lint/hal.tcl): SYNPRT
// Clock/reset renamed across CMSDK hierarchy (hclk→HCLK, hresetn→HRESETn)
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DIFCLK
// (already waived by nanosoc-multicore-system/lint/hal.tcl): DIFRST
// Typedef not in package — module-local typedefs are acceptable
// (already waived by nanosoc-multicore-system/lint/hal.tcl): TDOPKG
// Lowercase type names — SV convention for types
// (already waived by nanosoc-multicore-system/lint/hal.tcl): UCCONN
// FF without synchronous reset — async reset is sufficient
// (already waived by nanosoc-multicore-system/lint/hal.tcl): FFWNSR
// Unused port bits — APB paddr upper bits only partially decoded
// (already waived by nanosoc-multicore-system/lint/hal.tcl): USEPRT
// Unconnected output ports
// (already waived by nanosoc-multicore-system/lint/hal.tcl): UNCONO
// Combinational I/O paths — inherent to APB register decode (addr→slot_addr,
// data→slot_data, slot_rd_data→prdata). These are expected in a zero-wait-state
// APB slave register block.
// (already waived by tidelink/lint/hal.tcl): IOCOMB
// Multiple blocking assignments — prdata uses a case statement with a default
// value followed by specific overrides. This is standard RTL style.
-nocheck MULBAS
// CMSDK-specific warnings that leak through
// (already waived by nanosoc-multicore-system/lint/hal.tcl): OLDALW
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LOGNEG
// (already waived by nanosoc-multicore-system/lint/hal.tcl): LOGAND
// (already waived by nanosoc-multicore-system/lint/hal.tcl): BOUINC
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MEMRNM
// (already waived by nanosoc-multicore-system/lint/hal.tcl): MICAWS
// (already waived by nanosoc-multicore-system/lint/hal.tcl): BBXSIG
