#!/usr/bin/env python3
"""Regenerate hal_rules.tcl from the unit-level lint/hal.tcl files.

WHY THIS IS A SCRIPT AND NOT A HAND-EDITED FILE
    hal_rules.tcl started as a one-off hand merge. Two things went wrong that a
    hand merge cannot prevent:
      * it inherited `-nocheck MLTDRV` and `-nocheck CLKDMN` from the SoC's
        ruleset -- the exact rules `make elab-strict` and `make cdc` exist to
        catch (mutation-proven: MLTDRV 1->0, CLKDMN 1->0);
      * when that was corrected by hand, three rules that are NOT sign-off rules
        (FDTHRU, UCCONN, DFDRVS) were removed with them, leaving ~44 findings
        nobody had decided to gate on.
    Both are merge policy, so the merge is code. SIGNOFF_RULES is subtracted
    mechanically, and hal_lint.sh preflights the result.

    A unit ruleset that is correct for one block is not automatically correct for
    the integration. That is the whole reason this file exists.

    merge_hal_rules.py [--check]      --check = fail if the committed file is stale
"""
import os
import re
import sys
import argparse

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
OUT = os.path.join(HERE, "hal_rules.tcl")

# Must match hal_lint.sh:SIGNOFF_RULES and hal_report.py:NEVER_WAIVE.
SIGNOFF_RULES = {"MLTDRV", "CLKDMN", "INSYNC", "SIZMIS", "GLTASR",
                 "LATINF", "NODRIV", "UNCONI", "RSTSCB", "CMBCDC"}

UNITS = [
    "nanosoc-multicore-system/lint/hal.tcl",
    "tidelink/lint/hal.tcl",
    "tidechart/lint/hal.tcl",
    "nanosoc-multicore-system/ahb_qspi/lint/hal.tcl",
    "nanosoc-multicore-system/ethernet-subsystem-ahb/ethernet-mac-ahb/lint/hal.tcl",
    "nanosoc-multicore-system/inter-processor-communications-ahb/lint/hal.tcl",
    "nanosoc-multicore-system/ptp-hardware-clock-ahb/lint/hal.tcl",
]

HEADER = """// -----------------------------------------------------------------------------
// GENERATED by verif/lint/full/merge_hal_rules.py -- DO NOT EDIT BY HAND.
// Union of every unit-level lint/hal.tcl in the integration, MINUS the sign-off
// rules, which may never be waived at any level:
//     {signoff}
// hal_lint.sh preflights this file against that list and refuses to run if one
// reappears. Re-generate after changing any unit ruleset:
//     python3 verif/lint/full/merge_hal_rules.py
// -----------------------------------------------------------------------------
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    seen, lines, dropped, missing = {}, [], [], []
    for rel in UNITS:
        p = os.path.join(REPO, rel)
        if not os.path.isfile(p):
            missing.append(rel)
            continue
        body, kept = [], 0
        for raw in open(p, errors="replace").read().splitlines():
            m = re.match(r"^-nocheck\s+(\S+)\s*$", raw)
            if not m:
                # keep the justification comments that precede a rule
                if raw.startswith("//") and raw.strip() != "//":
                    body.append(raw)
                continue
            rule = m.group(1)
            if rule in SIGNOFF_RULES:
                dropped.append((rule, rel))
                body.append(f"// DROPPED (sign-off rule, never waivable): -nocheck {rule}")
                continue
            if rule in seen:
                body.append(f"// (already waived by {seen[rule]}): {rule}")
                continue
            seen[rule] = rel
            body.append(raw)
            kept += 1
        if kept:
            lines.append(f"\n// ===== from {rel}  ({kept} rule(s))")
            lines.extend(body)

    text = HEADER.format(signoff=" ".join(sorted(SIGNOFF_RULES))) + "\n".join(lines) + "\n"

    if a.check:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print(f"STALE: {OUT} does not match the unit rulesets. "
                  f"Run: python3 {os.path.relpath(__file__, REPO)}")
            return 1
        print(f"hal_rules.tcl is in step with the unit rulesets ({len(seen)} rules)")
        return 0

    open(OUT, "w").write(text)
    print(f"wrote {OUT}: {len(seen)} rules from {len(UNITS)-len(missing)} unit ruleset(s)")
    if dropped:
        print(f"  dropped {len(dropped)} sign-off rule instance(s):")
        for r, src in sorted(set(dropped)):
            print(f"    {r:8s} (would have been inherited from {src})")
    for m in missing:
        print(f"  NOTE: unit ruleset not found: {m}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
