#!/usr/bin/env python3
"""
Derive a Tempus-loadable MMMC from a routed Innovus database.

WHY THIS IS NEEDED
------------------
Tempus refuses to load this design's MMMC as written:

  ERROR (IMPESI-3490): cdB based analysis is not supported with CMMMC
                       configuration. ... Configure and run analysis in SMSC

and the load ABORTS — read_db returns without populating the design, so every
later command dies with the far less informative "Design must be in memory".

The design's three library sets each carry a `-si` section naming a Celtic
`.cdb` noise library (one per PVT corner: worst, best and typical).
Tempus supports those only in single-mode single-corner (SMSC) analysis, not
in the concurrent MMMC configuration this DB was saved with.

WHAT THIS DOES
--------------
Emits a copy of the DB's own viewDefinition.tcl with the `-si` sections
removed, and with ::IMEX::dataVar pinned to the DB directory (the original
derives it from `info script`, which would resolve to THIS file's directory
and silently break every library path).

WHAT IT COSTS — STATE IT, DO NOT BURY IT
----------------------------------------
Dropping `-si` means SIGNAL-INTEGRITY (crosstalk) ANALYSIS IS OFF. The P&R
flow's own post-route report header reads "Signoff Settings: SI On", so this
is a real reduction in scope relative to the in-flow number, not a
like-for-like comparison. A signoff that ships must either

  (a) run SMSC — one view per Tempus invocation, `.cdb` retained, two runs; or
  (b) replace the Celtic .cdb noise libraries with the ECSM/CCS noise data
      Tempus prefers, if the vendor package has it.

Both are morning decisions. This script exists so that tonight's run produces
a real, honest number with a NAMED limitation rather than no number at all.

The generated file is written under ASIC/sta/ and touches nothing in the
build tree, the P&R scripts, or inputs/*.sdc.
"""

import argparse
import os
import re
import sys


def strip_si(text):
    """
    Remove `-si\\n [list ...]` sections from create_library_set blocks.

    The viewDefinition emits them as a backslash-continued option:

        create_library_set -name typical_libset\\
           -timing\\
            [list a.lib b.lib]\\
           -si\\
            [list ${::IMEX::libVar}/mmmc/<stdcell-typ>.cdb]

    so the section runs from `-si` to the end of the bracketed list. Returns
    (new_text, n_removed).
    """
    out = []
    n = 0
    i = 0
    lines = text.splitlines(keepends=True)
    while i < len(lines):
        if re.match(r"^\s*-si\s*\\?\s*$", lines[i]):
            n += 1
            i += 1
            # consume the [list ... ] that follows, across continuations
            depth = 0
            started = False
            while i < len(lines):
                depth += lines[i].count("[") - lines[i].count("]")
                if "[" in lines[i]:
                    started = True
                i += 1
                if started and depth <= 0:
                    break
            # The removed section may have been the last option of the
            # command, in which case the PREVIOUS emitted line still ends in a
            # backslash and would swallow whatever comes next. Trim it.
            if out:
                stripped = out[-1].rstrip()
                if stripped.endswith("\\"):
                    out[-1] = stripped[:-1].rstrip() + "\n"
            continue
        out.append(lines[i])
        i += 1
    return "".join(out), n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", required=True, help="routed Innovus .dat directory")
    ap.add_argument("--out", required=True, help="MMMC file to write")
    args = ap.parse_args()

    vd = os.path.join(args.db, "viewDefinition.tcl")
    if not os.path.isfile(vd):
        print(f"FATAL: no viewDefinition.tcl in {args.db}", file=sys.stderr)
        return 1

    text = open(vd, errors="replace").read()
    new, n = strip_si(text)

    if n == 0:
        print("WARNING: no -si sections found. Either the DB never had SI "
              "libraries (in which case IMPESI-3490 has a different cause and "
              "you should not assume this file fixes it), or the emitted "
              "format changed and this script silently did nothing.",
              file=sys.stderr)

    db_abs = os.path.abspath(args.db)
    header = (
        "################################################################\n"
        "# GENERATED by ASIC/sta/make_sta_mmmc.py -- DO NOT EDIT BY HAND.\n"
        f"# Source: {vd}\n"
        f"# -si (Celtic .cdb noise) sections removed: {n}\n"
        "#\n"
        "# SI/CROSSTALK ANALYSIS IS OFF IN THIS CONFIGURATION.\n"
        "# The P&R flow reports 'Signoff Settings: SI On'; this does not.\n"
        "# See the header of make_sta_mmmc.py for why, and for the two ways\n"
        "# to get SI back.\n"
        "################################################################\n"
        "if {![namespace exists ::IMEX]} { namespace eval ::IMEX {} }\n"
        f"set ::IMEX::dataVar {db_abs}\n"
        "set ::IMEX::libVar ${::IMEX::dataVar}/libs\n"
    )

    # Drop the original's own dataVar/libVar derivation: it uses `info script`,
    # which in this file would point at ASIC/sta/ and resolve every library to
    # a path that does not exist.
    body = []
    for line in new.splitlines(keepends=True):
        if re.match(r"^\s*(if \{!\[namespace exists ::IMEX\]|set ::IMEX::(dataVar|libVar))", line):
            continue
        body.append(line)

    with open(args.out, "w") as fh:
        fh.write(header)
        fh.write("".join(body))

    print(f"wrote {args.out}  (-si sections removed: {n})")

    # Positive control: the output must not mention .cdb anywhere, and must
    # still define the views. A generator that produced an empty or truncated
    # file would otherwise look like success.
    produced = open(args.out, errors="replace").read()
    # Check only executable lines. The header comment above says the words
    # ".cdb noise" and an earlier version of this control matched its own
    # documentation and reported a failure that did not exist.
    code = "\n".join(l for l in produced.splitlines() if not l.lstrip().startswith("#"))
    problems = []
    if ".cdb" in code:
        problems.append("output still references a .cdb noise library")
    for req in ("create_library_set", "create_analysis_view", "set_analysis_view"):
        if req not in produced:
            problems.append(f"output has no {req}")
    if problems:
        for p in problems:
            print(f"FATAL: {p}", file=sys.stderr)
        return 1
    print("self-check ok: no .cdb references, view definitions intact")
    return 0


if __name__ == "__main__":
    sys.exit(main())
