#!/usr/bin/env python3
"""
sgdc_port_drift.py — cross-check every SpyGlass .sgdc in the tree against the
real RTL module port list it claims to constrain.

WHY THIS EXISTS
---------------
An `abstract_port` whose name no longer matches a real module port is silently
DROPPED by SpyGlass.  The port it was meant to constrain then falls back to a
default (typically a virtual clock, or whatever clock the tool infers for the
black-box boundary), which manufactures spurious crossings at best and MASKS
real ones at worst.  SpyGlass has a built-in detector for this — rule
`checkSGDC_05`, "abstract_port did not match any port" — but that rule is
routinely waived, at which point port drift becomes invisible.

This script is the licence-free, tool-free equivalent of that detector, plus
the reverse direction (real ports with no declaration at all).  It parses the
RTL directly, so it is definitive and can run in CI on any machine.

THE GOVERNING ASYMMETRY
-----------------------
A WRONG clock declaration MASKS real crossings.  A MISSING one only
over-reports.  So the two findings this script emits are not equally severe:

  STALE       declared-but-absent — the declaration is dead.  The port it was
              meant to cover (if it was renamed rather than deleted) is now
              UNDECLARED, i.e. defaulted.  Treat as high severity.
  UNDECLARED  present-but-undeclared — real port, no constraint.  Defaulted.
              Severity depends on whether the default is the right domain.

This script deliberately does NOT try to infer the correct clock domain for an
undeclared port.  Guessing a domain is the failure mode it exists to catch.

USAGE
  scripts/cdc/sgdc_port_drift.py                     # human-readable report
  scripts/cdc/sgdc_port_drift.py --markdown          # per-file markdown tables
  scripts/cdc/sgdc_port_drift.py --check             # exit 1 if any STALE found
  scripts/cdc/sgdc_port_drift.py --only tidelink     # filter by path substring

EXIT CODES
  0  no stale declarations (or --check not given)
  1  at least one stale declaration found (--check)
  2  usage / internal error
"""

from __future__ import annotations

import argparse
import fnmatch
import os
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

RTL_EXT = (".v", ".sv")
SKIP_DIR_PARTS = (
    os.sep + ".git" + os.sep,
    os.sep + "node_modules" + os.sep,
    os.sep + "AN.DB" + os.sep,
)

# Where a module definition is most likely to be the one actually compiled.
# Earlier == higher precedence.  local_overrides wins because the project
# flists deliberately read the override ahead of the vendor copy.
PATH_PRECEDENCE = (
    "/src/rtl/local_overrides/",
    "/src/rtl/",
    "/rtl/",
    "/logical/",
    "/deps/",
)

# Tool-generated / build-output territory.  SGDCs found here are SpyGlass's own
# autogenerated constraint dumps, not source, and must not appear in the report.
# RTL found here (gate netlists, packaged IP copies) is still indexed, but at
# the lowest precedence so a real source definition always wins.
GENERATED_PARTS = (
    os.sep + "build" + os.sep,
    os.sep + ".SG_SaveRestoreDB" + os.sep,
    os.sep + "spyglass_spysch" + os.sep,
    os.sep + "spyglass_reports" + os.sep,
    os.sep + "scratch_resolved" + os.sep,
    os.sep + "gate-sim" + os.sep,
    os.sep + "golden" + os.sep,
)


def is_generated(path: str) -> bool:
    """True if `path` is generated RTL rather than authored source."""
    return any(p in path for p in GENERATED_PARTS)


# ---------------------------------------------------------------------------
# RTL parsing
# ---------------------------------------------------------------------------

_BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.S)
_LINE_COMMENT = re.compile(r"//[^\n]*")
_DIRECTIVE = re.compile(r"^\s*`(?:ifdef|ifndef|else|elsif|endif|include|line|default_nettype|timescale|celldefine|endcelldefine|resetall|undef)\b[^\n]*",
                        re.M)

_KEYWORDS = {
    "input", "output", "inout", "ref", "wire", "reg", "logic", "bit", "byte",
    "shortint", "int", "longint", "integer", "time", "real", "shortreal",
    "signed", "unsigned", "var", "supply0", "supply1", "tri", "triand",
    "trior", "tri0", "tri1", "wand", "wor", "uwire", "interconnect",
    "parameter", "localparam", "const", "static", "automatic",
}


def _strip_comments(text: str) -> str:
    """Remove comments, keeping both arms of any preprocessor conditional."""
    text = _BLOCK_COMMENT.sub(" ", text)
    text = _LINE_COMMENT.sub("", text)
    # Preprocessor conditionals: drop the directive line but KEEP both arms.
    # A superset of ports is the safe direction here -- an extra port shows up
    # as "undeclared" (over-report), a dropped one would hide real drift.
    text = _DIRECTIVE.sub("", text)
    return text


def _balanced(text: str, start: int, open_ch: str = "(", close_ch: str = ")") -> tuple[str, int]:
    """Return (contents-without-outer-delims, index-just-past-close)."""
    assert text[start] == open_ch
    depth = 0
    i = start
    while i < len(text):
        c = text[i]
        if c == open_ch:
            depth += 1
        elif c == close_ch:
            depth -= 1
            if depth == 0:
                return text[start + 1:i], i + 1
        i += 1
    return text[start + 1:], len(text)


def _split_top_level(text: str, sep: str = ",") -> list[str]:
    """Split on `sep` at bracket depth zero."""
    out, depth, cur = [], 0, []
    for c in text:
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        if c == sep and depth == 0:
            out.append("".join(cur))
            cur = []
        else:
            cur.append(c)
    if cur:
        out.append("".join(cur))
    return [s.strip() for s in out if s.strip()]


_BRACKETS = re.compile(r"\[[^\[\]]*\]")
_IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_$]*")


def _port_name_from_decl(item: str) -> str | None:
    """Extract the declared port identifier from one ANSI port-list item."""
    # Drop any default value assignment ("input wire x = 1'b0").
    item = item.split("=")[0]
    # Repeatedly remove bracket groups so packed/unpacked ranges cannot be
    # mistaken for the name.
    prev = None
    while prev != item:
        prev = item
        item = _BRACKETS.sub(" ", item)
    # Drop scope-resolution qualified type names (pkg::type_t).
    item = re.sub(r"[A-Za-z_][A-Za-z0-9_$]*\s*::\s*", "", item)
    toks = _IDENT.findall(item)
    if not toks:
        return None
    name = toks[-1]
    if name in _KEYWORDS:
        return None
    return name


@dataclass
class ModuleDef:
    """One module declaration: its name, the file it came from, and its ports."""
    name: str
    path: str
    ports: list[str] = field(default_factory=list)
    ansi: bool = True


_MODULE_RE = re.compile(r"\bmodule\s+([A-Za-z_][A-Za-z0-9_$]*)")


def parse_modules(path: str) -> list[ModuleDef]:
    """Every module declared in one RTL file."""
    try:
        with open(path, "r", errors="replace") as fh:
            raw = fh.read()
    except OSError:
        return []
    if "module" not in raw:
        return []
    text = _strip_comments(raw)
    mods: list[ModuleDef] = []
    for m in _MODULE_RE.finditer(text):
        name = m.group(1)
        i = m.end()
        # Skip attributes / import / parameter block until the port list "(".
        guard = 0
        while i < len(text) and guard < 64:
            guard += 1
            while i < len(text) and text[i].isspace():
                i += 1
            if i >= len(text):
                break
            if text[i] == "#":
                j = text.find("(", i)
                if j < 0:
                    break
                _, i = _balanced(text, j)
                continue
            if text[i] == "(":
                break
            if text[i] == ";":
                # module with no port list at all
                i = -1
                break
            # import/attribute tokens -- step over one token
            tm = _IDENT.match(text, i)
            if tm:
                i = tm.end()
                # swallow "::*" and separators
                while i < len(text) and text[i] in " \t\r\n:*.,":
                    i += 1
                continue
            i += 1
        if i is None or i < 0 or i >= len(text) or text[i] != "(":
            mods.append(ModuleDef(name, path, [], True))
            continue
        header, after = _balanced(text, i)
        body_end = text.find("endmodule", after)
        body = text[after:body_end if body_end > 0 else len(text)]

        items = _split_top_level(header)
        has_dir = any(re.match(r"\s*(input|output|inout|ref)\b", it) for it in items)
        ports: list[str] = []
        if has_dir:
            # ANSI style; direction may be inherited from the previous item.
            for it in items:
                nm = _port_name_from_decl(it)
                if nm:
                    ports.append(nm)
            ansi = True
        else:
            # Non-ANSI: header is a bare name list, directions live in the body.
            for it in items:
                it2 = _BRACKETS.sub(" ", it)
                toks = _IDENT.findall(it2)
                if len(toks) == 1 and toks[0] not in _KEYWORDS:
                    ports.append(toks[0])
            ansi = False
            if not ports:
                # .name(sig) style port map or something unparsed -- fall back
                # to body direction declarations.
                for dm in re.finditer(
                        r"\b(input|output|inout)\b([^;]*);", body):
                    seg = _BRACKETS.sub(" ", dm.group(2))
                    seg = re.sub(r"\b(wire|reg|logic|signed|unsigned|tri)\b", " ", seg)
                    for nm in _IDENT.findall(seg):
                        if nm not in _KEYWORDS:
                            ports.append(nm)
        # de-dup, preserve order
        seen, uniq = set(), []
        for p in ports:
            if p not in seen:
                seen.add(p)
                uniq.append(p)
        mods.append(ModuleDef(name, path, uniq, ansi))
    return mods


# ---------------------------------------------------------------------------
# RTL index
# ---------------------------------------------------------------------------

def build_index(root: str, wanted: set[str] | None = None) -> dict[str, list[ModuleDef]]:
    """Index module definitions across the tree.

    `wanted` restricts the deep parse to files whose raw text mentions at least
    one design name we actually need.  The tree holds ~11k RTL files, many of
    them multi-megabyte gate netlists; the full comment-strip + port parse on
    all of them takes minutes, while a substring pre-filter takes seconds and
    cannot produce a false negative (a file that defines `module foo`
    necessarily contains the substring "foo").
    """
    index: dict[str, list[ModuleDef]] = defaultdict(list)
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames
                       if d not in (".git", "node_modules", "AN.DB", "__pycache__")]
        for fn in filenames:
            if not fn.endswith(RTL_EXT):
                continue
            full = os.path.join(dirpath, fn)
            if any(p in full for p in SKIP_DIR_PARTS):
                continue
            if wanted is not None:
                try:
                    with open(full, "r", errors="replace") as fh:
                        raw = fh.read()
                except OSError:
                    continue
                if "module" not in raw or not any(w in raw for w in wanted):
                    continue
            for mod in parse_modules(full):
                if wanted is None or mod.name in wanted:
                    index[mod.name].append(mod)
    return index


def _precedence(path: str) -> int:
    """Sort key deciding which copy of a duplicated module name wins."""
    rel = path.replace(REPO_ROOT, "")
    base = 100 if is_generated(rel) else 0
    for i, frag in enumerate(PATH_PRECEDENCE):
        if frag in rel:
            return base + i
    return base + len(PATH_PRECEDENCE)


def pick_definition(defs: list[ModuleDef]) -> tuple[ModuleDef, bool]:
    """Choose the definition most likely to be compiled; flag port-set conflict."""
    ordered = sorted(defs, key=lambda d: (_precedence(d.path), len(d.path)))
    best = ordered[0]
    conflict = any(set(d.ports) != set(best.ports) for d in ordered[1:])
    return best, conflict


# ---------------------------------------------------------------------------
# SGDC parsing
# ---------------------------------------------------------------------------

@dataclass
class Decl:
    """One SGDC declaration line, parsed into its kind and arguments."""
    kind: str          # abstract_port | clock | reset | quasi_static | set_case_analysis
    spec: str          # the name/pattern as written
    clock: str | None  # -clock argument, when present
    line: int


@dataclass
class SgdcBlock:
    """One `current_design` block of an SGDC file and the declarations inside it."""
    design: str
    line: int
    decls: list[Decl] = field(default_factory=list)


def parse_sgdc(path: str) -> list[SgdcBlock]:
    """Parse an SGDC file into its per-design blocks."""
    with open(path, "r", errors="replace") as fh:
        raw = fh.readlines()

    # Join continuation lines, remembering the first physical line number.
    logical: list[tuple[int, str]] = []
    buf, start = "", 0
    for n, line in enumerate(raw, 1):
        s = line.rstrip("\n")
        if not buf:
            start = n
        if s.rstrip().endswith("\\"):
            buf += s.rstrip()[:-1] + " "
            continue
        buf += s
        logical.append((start, buf))
        buf = ""
    if buf:
        logical.append((start, buf))

    blocks: list[SgdcBlock] = []
    cur = SgdcBlock("<none>", 0)
    blocks.append(cur)

    for lineno, text in logical:
        # strip trailing comment (SGDC uses '#'; '//' also appears)
        t = re.split(r"(?<!\S)#", text, maxsplit=1)[0]
        t = t.split("//")[0].strip()
        if not t:
            continue
        toks = t.split()
        cmd = toks[0]
        if cmd == "current_design":
            name = toks[1].strip('"') if len(toks) > 1 else "<unnamed>"
            cur = SgdcBlock(name, lineno)
            blocks.append(cur)
            continue
        if cmd == "abstract_port":
            ports = _tcl_opt(t, "-ports")
            clk = _tcl_opt(t, "-clock")
            if ports:
                for p in ports.split():
                    cur.decls.append(Decl("abstract_port", p.strip('"'), clk, lineno))
            continue
        if cmd in ("clock", "reset", "quasi_static", "set_case_analysis",
                   "assume_path", "num_flops", "cdc_false_path"):
            nm = _tcl_opt(t, "-name")
            if nm:
                for p in nm.split():
                    cur.decls.append(Decl(cmd, p.strip('"'), None, lineno))
            continue
    return [b for b in blocks if b.decls or b.design != "<none>"]


def _tcl_opt(text: str, opt: str) -> str | None:
    """Value of Tcl option `opt` in `text`, or None if it is absent."""
    m = re.search(re.escape(opt) + r"\s+(\"[^\"]*\"|\{[^}]*\}|\S+)", text)
    if not m:
        return None
    v = m.group(1)
    if v[0] in "\"{":
        v = v[1:-1]
    return v


# ---------------------------------------------------------------------------
# Matching
# ---------------------------------------------------------------------------

def spec_to_glob(spec: str) -> str:
    """An SGDC port spec to an fnmatch pattern.

    `foo[*]` means "the vector foo" -- SpyGlass matches the port named `foo`.
    `foo_*`  is a genuine name wildcard.
    """
    s = spec.strip()
    s = re.sub(r"\[\s*\*\s*\]$", "", s)          # foo[*]  -> foo
    s = re.sub(r"\[\s*\d+\s*:\s*\d+\s*\]$", "", s)  # foo[3:0] -> foo
    s = re.sub(r"\[\s*\d+\s*\]$", "", s)          # foo[3]  -> foo
    return s


@dataclass
class FileResult:
    """Per-SGDC-file findings, one entry per `current_design` block."""
    path: str
    blocks: list[dict] = field(default_factory=list)


def analyse(sgdc_path: str, index: dict[str, list[ModuleDef]]) -> FileResult:
    """Compare one SGDC file against the RTL: which declared ports still exist."""
    res = FileResult(sgdc_path)
    for blk in parse_sgdc(sgdc_path):
        if blk.design == "<none>":
            if not blk.decls:
                continue
        entry: dict = {
            "design": blk.design,
            "line": blk.line,
            "found": False,
            "rtl_path": None,
            "conflict": False,
            "stale_ports": [],
            "stale_names": [],
            "undeclared": [],
            "declared": 0,
            "nports": 0,
            "hier": [],
            "netlist_only": False,
        }
        defs = index.get(blk.design)
        if not defs:
            entry["stale_ports"] = [(d.spec, d.line) for d in blk.decls
                                    if d.kind == "abstract_port"]
            entry["stale_names"] = [(d.kind, d.spec, d.line) for d in blk.decls
                                    if d.kind != "abstract_port"]
            res.blocks.append(entry)
            continue
        mdef, conflict = pick_definition(defs)
        entry["found"] = True
        entry["rtl_path"] = os.path.relpath(mdef.path, REPO_ROOT)
        entry["conflict"] = conflict
        entry["nports"] = len(mdef.ports)
        # A current_design whose ONLY definition is a build artefact or a
        # gate-sim golden netlist is itself a drift finding: the SGDC is
        # constraining a unit that no longer has source RTL, and its
        # declarations will validate happily against the stale netlist while
        # bearing no relation to what the SoC actually builds.
        entry["netlist_only"] = all(is_generated(d.path) for d in defs)

        # RTL text of the chosen definition, for "is this an internal net?"
        try:
            with open(mdef.path, errors="replace") as fh:
                rtl_text = _strip_comments(fh.read())
        except OSError:
            rtl_text = ""
        rtl_idents = set(_IDENT.findall(rtl_text))

        covered: set[str] = set()
        for d in blk.decls:
            if d.kind == "abstract_port":
                pat = spec_to_glob(d.spec)
                hits = fnmatch.filter(mdef.ports, pat)
                if hits:
                    covered.update(hits)
                else:
                    entry["stale_ports"].append((d.spec, d.line))
            else:
                nm = spec_to_glob(d.spec)
                if "/" in nm:
                    # hierarchical reference -- not a port of this module by
                    # construction; record separately, do not call it stale.
                    entry["hier"].append((d.kind, d.spec, d.line))
                    continue
                hits = fnmatch.filter(mdef.ports, nm)
                if hits:
                    covered.update(hits)
                elif not any(fnmatch.fnmatch(i, nm) for i in rtl_idents):
                    # neither a port nor any identifier in the module source
                    entry["stale_names"].append((d.kind, d.spec, d.line))
        entry["declared"] = len(covered)
        entry["undeclared"] = [p for p in mdef.ports if p not in covered]
        res.blocks.append(entry)
    return res


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def find_sgdc(root: str, include_generated: bool = False) -> list[str]:
    """Every .sgdc under `root`, skipping generated trees unless asked for them."""
    out = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in (".git", "node_modules", "AN.DB")]
        for fn in filenames:
            if not fn.endswith(".sgdc"):
                continue
            full = os.path.join(dirpath, fn)
            if not include_generated and is_generated(full):
                continue
            out.append(full)
    return sorted(out)


def _fmt_list(items, limit=None):
    """Format a list for the report, truncating at `limit`."""
    if not items:
        return "—"
    if limit and len(items) > limit:
        return ", ".join(f"`{i}`" for i in items[:limit]) + f", … (+{len(items)-limit} more)"
    return ", ".join(f"`{i}`" for i in items)


def main(argv=None) -> int:
    """Scan the SGDC files and report every declaration that no longer matches the RTL."""
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=REPO_ROOT)
    ap.add_argument("--markdown", action="store_true", help="emit markdown tables")
    ap.add_argument("--check", action="store_true", help="exit 1 on any stale declaration")
    ap.add_argument("--only", default=None, help="only .sgdc paths containing this substring")
    ap.add_argument("--full", action="store_true", help="do not truncate long lists")
    ap.add_argument("--include-generated", action="store_true",
                    help="also scan SpyGlass-autogenerated .sgdc under build/ etc.")
    args = ap.parse_args(argv)

    root = os.path.abspath(args.root)
    sgdcs = find_sgdc(root, args.include_generated)
    if args.only:
        sgdcs = [p for p in sgdcs if args.only in p]
    if not sgdcs:
        print("no .sgdc files found", file=sys.stderr)
        return 2

    wanted: set[str] = set()
    for p in sgdcs:
        for blk in parse_sgdc(p):
            if blk.design not in ("<none>", "<unnamed>"):
                wanted.add(blk.design)
    index = build_index(root, wanted)

    total_stale = 0
    total_undecl = 0
    out: list[str] = []
    limit = None if args.full else 12

    for p in sgdcs:
        rel = os.path.relpath(p, root)
        res = analyse(p, index)
        blocks = [b for b in res.blocks if b["design"] != "<none>"]
        if args.markdown:
            out.append(f"### `{rel}`\n")
        else:
            out.append(f"\n=== {rel}")
        if not blocks:
            out.append("_no `current_design` block_\n" if args.markdown else "  (no current_design)")
            continue
        if args.markdown:
            out.append("| `current_design` | RTL found | ports | declared | STALE `abstract_port` | STALE name decls | UNDECLARED ports |")
            out.append("|---|---|--:|--:|---|---|---|")
        for b in blocks:
            total_stale += len(b["stale_ports"]) + len(b["stale_names"])
            total_undecl += len(b["undeclared"])
            if args.markdown:
                found = f"`{b['rtl_path']}`" if b["found"] else "**NOT FOUND**"
                if b["conflict"]:
                    found += " ⚠︎multi-def"
                if b["netlist_only"]:
                    found += " ⚠︎**netlist-only**"
                sp = _fmt_list([f"{s} (L{l})" for s, l in b["stale_ports"]], limit)
                sn = _fmt_list([f"{k} {s} (L{l})" for k, s, l in b["stale_names"]], limit)
                ud = _fmt_list(b["undeclared"], limit)
                out.append(f"| `{b['design']}` | {found} | {b['nports']} | {b['declared']} | {sp} | {sn} | {ud} |")
            else:
                out.append(f"  current_design {b['design']} (L{b['line']})")
                out.append(f"    rtl        : {b['rtl_path'] or 'NOT FOUND'}"
                           + ("  [MULTIPLE DEFINITIONS DISAGREE]" if b["conflict"] else "")
                           + ("  [NETLIST/ARTEFACT ONLY - no source RTL defines this unit]"
                              if b["netlist_only"] else ""))
                out.append(f"    ports      : {b['nports']}   declared: {b['declared']}")
                if b["stale_ports"]:
                    out.append(f"    STALE abstract_port ({len(b['stale_ports'])}):")
                    for s, l in b["stale_ports"]:
                        out.append(f"        L{l:<5} {s}")
                if b["stale_names"]:
                    out.append(f"    STALE name decls ({len(b['stale_names'])}):")
                    for k, s, l in b["stale_names"]:
                        out.append(f"        L{l:<5} {k} {s}")
                if b["hier"]:
                    out.append(f"    hierarchical (not checked) ({len(b['hier'])}):")
                    for k, s, l in b["hier"]:
                        out.append(f"        L{l:<5} {k} {s}")
                if b["undeclared"]:
                    out.append(f"    UNDECLARED ports ({len(b['undeclared'])}):")
                    for chunk in range(0, len(b["undeclared"]), 6):
                        out.append("        " + "  ".join(b["undeclared"][chunk:chunk + 6]))
        if args.markdown:
            out.append("")

    print("\n".join(out))
    print(f"\nTOTAL: {len(sgdcs)} sgdc files, {total_stale} stale declarations, "
          f"{total_undecl} undeclared ports")

    if args.check and total_stale:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
