source ../scripts/procs.tcl


set hdl_file_list ../scripts/read_flist.tcl

# System Paths, please edit for your system
set io_lib_dir $::env(TSMC_65_HOME)/CMOS/LP/IO2.5V/iolib/STAGGERED/tphn65lpgv2od3_sl_210a_FE/TSMCHOME/digital/Front_End/timing_power_noise/NLDM/tphn65lpgv2od3_sl_210a/
set sc_lib_dir $::env(TSMC_65_HOME)/CMOS/LP/stclib/9-track/tcbn65lp-set/tcbn65lp_220a_FE/TSMCHOME/digital/Front_End/timing_power_noise/NLDM/tcbn65lp_220a

# Automatically setup !Don't touch!
set rf_32k_dir /research/precompiled_mems/TSMC65/rf_32k
set rf_16k_dir /research/precompiled_mems/TSMC65/rf_16k/ 
set rf_08k_dir /research/precompiled_mems/TSMC65/rf_08k/ 
set flash_cache_data_dir /research/precompiled_mems/TSMC65/flash_cache_data
set flash_cache_tag_dir /research/precompiled_mems/TSMC65/flash_cache_tag

set bootrom_dir $::env(NANOSOC_ETH_CHIPLET_HOME)/ASIC/romlibs/cc_rom
set eth_rom_dir $::env(NANOSOC_ETH_CHIPLET_HOME)/ASIC/romlibs/eth_rom

set lib_search_path_list "$io_lib_dir $sc_lib_dir $rf_32k_dir $rf_16k_dir $rf_08k_dir $bootrom_dir $eth_rom_dir $flash_cache_data_dir $flash_cache_tag_dir"

# Libraries for Synthesis
set BASE_LIB tcbn65lpwc.lib
set RF_32K_LIB rf_32k_ss_1p08v_1p08v_125c.lib
set RF_LIB rf_16k_ss_1p08v_1p08v_125c.lib
set RF_08K rf_08k_ss_1p08v_1p08v_125c.lib
set ROM_LIB rom_via_ss_1p08v_1p08v_125c.lib
set ETH_ROM_LIB eth_rom_via_ss_1p08v_1p08v_125c.lib
set FLASH_DATA_LIB flash_cache_data_ss_1p08v_1p08v_125c.lib
set FLASH_TAG_LIB flash_cache_tag_ss_1p08v_1p08v_125c.lib

set IO_PAD_DRIVER tphn65lpgv2od3_slwc.lib

set syn_lib_list [list \
    $BASE_LIB \
    $RF_LIB \
    $RF_08K \
    $RF_32K_LIB \
    $IO_PAD_DRIVER \
    $ROM_LIB \
    $ETH_ROM_LIB \
    $FLASH_DATA_LIB \
    $FLASH_TAG_LIB \
    ]

set block_name nanosoc_eth_chiplet_pads

set LOG_DIR ../logs
set REPORT_DIR ../reports
set OUT_DIR ../outputs

set top_level_hdl $::env(NANOSOC_ETH_CHIPLET_HOME)/ASIC/tech_wrappers/tsmc65/nanosoc_eth_chiplet_pads.v
set constraints_file ../inputs/constraints.sdc

set DFT 0

set power_nets {VDD VDDACC VDDIO}
set ground_nets {VSS VSSIO}


# Set library paths 
# !! EDIT THIS TO YOUR PATHS IN YOUR ENVIRONMENT
set TECH_LEF /home/dwn1c21/SoC-Labs/util/PRTF_EDI_65nm_001_Cad_V24a/PRTF_EDI_N65_9M_6X1Z1U_RDL.24a.tlef
#$::env(PHYS_IP)/arm/tsmc/cln65lp/arm_tech/r2p0/lef/1p9m_6x2z/sc12_tech.lef
set BASE_LEF $::env(PHYS_IP)/arm/tsmc/cln65lp/sc12_base_rvt/r0p0/lef/sc12_cln65lp_base_rvt.lef
set IO_PAD_LEF $::env(TSMC_65_HOME)/CMOS/LP/IO2.5V/iolib/STAGGERED/tphn65lpgv2od3_sl_210a_FE/TSMCHOME/digital/Back_End/lef/tphn65lpgv2od3_sl_210a/mt_2/9lm/lef/tphn65lpgv2od3_sl_9lm.lef
set IO_PAD_DRIVER_LEF /home/dwn1c21/SoC-Labs/phys_ip/TSMC/65/CMOS/LP/IO2.5V/iolib/linear/tpdn65lpnv2od3_200a_FE/TSMCHOME/digital/Back_End/lef/tpdn65lpnv2od3_140b/mt_2/9lm/lef/tpdn65lpnv2od3_9lm.lef


# !! THESE SHOULD BE CORRECT FOR ANY ENVIRONMENT AS THEY ARE GENERATED BY MAKEFILE
set RF32_LEF $rf_32k_dir/rf_32k.lef
set RF16_LEF $rf_16k_dir/rf_16k.lef
set RF8_LEF $rf_08k_dir/rf_08k.lef
set CC_ROM_LEF $bootrom_dir/rom_via.lef
set ETH_ROM_LEF $eth_rom_dir/eth_rom_via.lef
set FLASH_DATA_LEF $flash_cache_data_dir/flash_cache_data.lef
set FLASH_TAG_LEF $flash_cache_tag_dir/flash_cache_tag.lef

set lef_file_list [list \
    ${TECH_LEF} \
    ${BASE_LEF} \
    ${IO_PAD_LEF} \
    ${IO_PAD_DRIVER_LEF} \
    ${RF32_LEF} \
    ${RF16_LEF} \
    ${RF8_LEF} \
    ${CC_ROM_LEF} \
    ${ETH_ROM_LEF} \
    ${FLASH_DATA_LEF} \
    ${FLASH_TAG_LEF} \
    ]


