###############################################################
#  Auto-generated by:   nanosoc_gen SoCPadRingBackend (doc 07 M6)
#  Template:            nanosoc_io_plan.io.j2
# Generated: 2026-07-10 11:15:15
#  Design:              nanosoc_chip_pads_tsmc65lp_multicore
#  Technology/variant:  tsmc65lp multicore
#
#  Cadence Innovus IO placement TEMPLATE (write_io_file -locations -template
#  shape).  The per-side instance ORDER is faithful to the pin-map ring/side
#  data; the offset= values are EVENLY-SPACED PLACEHOLDERS — real placement is
#  a PnR (Innovus) output, not derivable from the RTL model.
#
#  Copyright 2026, SoC Labs (www.soclabs.org)
###############################################################

(globals
    version = 3
	space=42
    io_order = default
)
(iopad
	( topleft 
		(inst name="uPAD_CORNER_TL" orientation=R270 cell=PCORNER_G)
	)
    (top
		(inst  name="uPAD_VDDIO_T_0"	place_status=fixed offset=150 )
		(inst  name="uPAD_VDD_T_0"		space=55 place_status=fixed )
		(inst  name="uPAD_VSS_T_0"		space=55 place_status=fixed )
		(inst  name="uPAD_NRST_I"		space=55 place_status=fixed )
		(inst  name="uPAD_SWDCK_I"		space=55 place_status=fixed )
		(inst  name="uPAD_CLK_I"		space=55 place_status=fixed )
		(inst  name="uPAD_TEST_I"		space=55 place_status=fixed )
		(inst  name="uPAD_SE_I"			space=55 place_status=fixed )
		(inst  name="uPAD_VDD_T_1"		space=55 place_status=fixed )
		(inst  name="uPAD_SWDIO_IO"		space=55 place_status=fixed )
		(inst  name="uPAD_VSS_T_1"		space=55 place_status=fixed )
		(inst  name="uPAD_VDDIO_T_1"	space=55 place_status=fixed )
		(inst  name="uPAD_VDDIO_T_2"	space=55 place_status=fixed )
		(inst  name="uPAD_VSSIO_T_0"	space=55 place_status=fixed )
		(inst  name="uPAD_VSSIO_T_1"	space=55 place_status=fixed )
		(inst  name="uPAD_VDD_T_2"		space=55 place_status=fixed )
		(inst  name="uPAD_VSSIO_T_2"	space=55 place_status=fixed )


    )
	(bottomleft
		(inst name="uPAD_CORNER_BL" orientation=R0 cell=PCORNER_G)
	)
    (left
		(inst  name="uPAD_TL_RX_0"			place_status=fixed  offset=150 )
		(inst  name="uPAD_TL_RX_1"	 		place_status=fixed )
		(inst  name="uPAD_TL_RX_2"	 		place_status=fixed )
		(inst  name="uPAD_TL_RX_3"			place_status=fixed )
		(inst  name="uPAD_VDDIO_L_0"	 	place_status=fixed )
		(inst  name="uPAD_VSSIO_L_0"	 	place_status=fixed )
		(inst  name="uPAD_TL_CLK_RX"	 	place_status=fixed )
		(inst  name="uPAD_TL_RX_4"			place_status=fixed )
		(inst  name="uPAD_TL_RX_5"			place_status=fixed )
		(inst  name="uPAD_TL_RX_6"	 		place_status=fixed )
		(inst  name="uPAD_TL_RX_7"	 		place_status=fixed )
		(inst  name="uPAD_I2C_SCL"	 		place_status=fixed )
		(inst  name="uPAD_I2C_SDA"	 		place_status=fixed )
		(inst  name="uPAD_VDDIO_L_1"	 	place_status=fixed )
		(inst  name="uPAD_VSSIO_L_1"	 	place_status=fixed )
		(inst  name="uPAD_TL_TX_0"	 		place_status=fixed )
		(inst  name="uPAD_TL_TX_1"	 		place_status=fixed )
		(inst  name="uPAD_TL_TX_2"	 		place_status=fixed )
		(inst  name="uPAD_TL_TX_3"	 		place_status=fixed )
		(inst  name="uPAD_VDDIO_L_2"	 	place_status=fixed )
		(inst  name="uPAD_VSSIO_L_2"	 	place_status=fixed )
		(inst  name="uPAD_TL_CLK_TX"	 	place_status=fixed )
		(inst  name="uPAD_TL_TX_4"	 		place_status=fixed )
		(inst  name="uPAD_TL_TX_5"	 		place_status=fixed )
		(inst  name="uPAD_TL_TX_6"	 		place_status=fixed )
		(inst  name="uPAD_TL_TX_7"	 		place_status=fixed )
    )
	(bottomright
		(inst name="uPAD_CORNER_BR" orientation=R90 cell=PCORNER_G)
	)
    (bottom
		(inst  name="uPAD_VDDIO_B_0"	 	place_status=fixed  offset=150 )
		(inst  name="uPAD_VSSIO_B_0"	 	space=55	place_status=fixed )
		(inst  name="uPAD_VDD_B_1"	 		space=55	place_status=fixed )
		(inst  name="uPAD_VSS_B_0"	 		space=55	place_status=fixed )
		(inst  name="uPAD_QSPI_IO_0"	 	space=55	place_status=fixed )
		(inst  name="uPAD_QSPI_IO_1"	 	space=55	place_status=fixed )
		(inst  name="uPAD_QSPI_IO_2"	 	space=55	place_status=fixed )
		(inst  name="uPAD_VDDIO_B_1"	 	space=55	place_status=fixed )
		(inst  name="uPAD_VSSIO_B_1"	 	space=55	place_status=fixed )
		(inst  name="uPAD_QSPI_IO_3"	 	space=55	place_status=fixed )
		(inst  name="uPAD_QSPI_SCLK"	 	space=55	place_status=fixed )
		(inst  name="uPAD_QSPI_nCS"	 		space=55	place_status=fixed )
		(inst  name="uPAD_VDD_B_0"	 		space=55	place_status=fixed )
		(inst  name="uPAD_VSSIO_B_2"	 	space=55	place_status=fixed )
		(inst  name="uPAD_VDD_B_2"	 		space=55	place_status=fixed )
		(inst  name="uPAD_VSS_B_1"	 		space=55	place_status=fixed )
		(inst  name="uPAD_VDDIO_B_2"	 	space=55	place_status=fixed )

    )
	(topright
		(inst name="uPAD_CORNER_TR" orientation=R180 cell=PCORNER_G)
	)
    (right
		(inst  name="uPAD_VDDIO_R_0"	 	place_status=fixed   offset=150)
		(inst  name="uPAD_VSSIO_R_0"	 	space=55	place_status=fixed )
		(inst  name="uPAD_RMII_MDC"	 		space=55	place_status=fixed )
		(inst  name="uPAD_RMII_REF_CLK"	 	space=55	place_status=fixed )
		(inst  name="uPAD_RMII_RXD0"	 	space=55	place_status=fixed )
		(inst  name="uPAD_VDDIO_R_1"	 	space=55	place_status=fixed )
		(inst  name="uPAD_VSSIO_R_1"	 	space=55	place_status=fixed )
		(inst  name="uPAD_RMII_RXD1"	 	space=55	place_status=fixed )
		(inst  name="uPAD_RMII_TXD0"	 	space=55	place_status=fixed )
		(inst  name="uPAD_RMII_TXD1"	 	space=55	place_status=fixed )
		(inst  name="uPAD_RMII_TX_EN"	 	space=55	place_status=fixed )
		(inst  name="uPAD_RMII_MDIO"	 	space=55	place_status=fixed )
		(inst  name="uPAD_RMII_CRS_DV"		space=55	place_status=fixed)
		(inst  name="uPAD_VDDIO_R_2"	 	space=55	place_status=fixed )
		(inst  name="uPAD_VSSIO_R_2"	 	space=55	place_status=fixed )
		(inst  name="uPAD_HOST_IO_0"	 	space=55	place_status=fixed )
		(inst  name="uPAD_HOST_IO_1"	 	space=55	place_status=fixed )
		(inst  name="uPAD_HOST_IO_2"	 	space=55	place_status=fixed )
		(inst  name="uPAD_HOST_IO_3"	 	space=55	place_status=fixed )
		(inst  name="uPAD_HOST_IO_4"	 	space=55	place_status=fixed )
		(inst  name="uPAD_HOST_IO_5"	 	space=55	place_status=fixed )
		(inst  name="uPAD_HOST_IO_6"	 	space=55	place_status=fixed )
    )
)
