#!/usr/bin/env bash
#-----------------------------------------------------------------------------
# package_submission.sh — assemble the tapeout hand-off bundle
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access license.
#
# Copyright 2026, SoC Labs (www.soclabs.org)
#-----------------------------------------------------------------------------
# Produces ONE zip to hand to the foundry or MPW broker, plus a MANIFEST that
# states what is in it, what it was built from, and — the part that matters —
# WHAT IS NOT DONE. A bundle that does not declare its own gaps invites somebody
# downstream to assume they were covered.
#
# The single most important thing recorded here: this GDS IS NOT SELF-CONTAINED.
# config.tcl's gds_merge_list holds only the 8 memory macros, because the PDK on
# this site ships LEF/liberty/Milkyway but NO GDS and NO CDL for tcbn65lp or the
# IO libraries. Standard cells, IO drivers and bond pads are therefore empty
# cell references and MUST be merged by whoever holds the foundry data.
#
# Usage:  package_submission.sh [output-dir]
# Exits non-zero if the GDS is absent — there is nothing to submit without it.
#-----------------------------------------------------------------------------
set -euo pipefail

ASIC_DIR="${ASIC_DIR:-ASIC/genus-innovus}"
BLOCK="${BLOCK:-nanosoc_eth_chiplet_pads}"
OUT="$ASIC_DIR/outputs"
REP="$ASIC_DIR/reports"
DEST="${1:-$ASIC_DIR/submission}"

GDS="$OUT/$BLOCK.gds"
[ -s "$GDS" ] || { echo "FAIL: no GDSII at $GDS — nothing to package." >&2; exit 1; }

SHA=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
DIRTY=""
git diff --quiet HEAD 2>/dev/null || DIRTY="-dirty"
STAMP=$(date -u +%Y%m%dT%H%M%SZ)
NAME="${BLOCK}_${SHA}${DIRTY}_${STAMP}"
STAGE="$DEST/$NAME"

mkdir -p "$STAGE"
echo "== staging $NAME =="

for f in "$BLOCK.gds" "${BLOCK}_pnr.v" "${BLOCK}_pnr.sdf" "${BLOCK}_syn.sdc"; do
    if [ -s "$OUT/$f" ]; then cp -p "$OUT/$f" "$STAGE/"; echo "  + $f"
    else echo "  ! MISSING $f"; fi
done
[ -d "$REP" ] && cp -rp "$REP" "$STAGE/reports" && echo "  + reports/"

# --- manifest ---------------------------------------------------------------
M="$STAGE/MANIFEST.txt"
{
    echo "nanosoc_eth_chiplet — tapeout hand-off bundle"
    echo "============================================="
    echo "generated   : $STAMP (UTC)"
    echo "built on    : $(hostname -s)"
    echo "repo commit : $(git rev-parse HEAD 2>/dev/null || echo unknown)$DIRTY"
    echo
    echo "submodules:"
    git submodule status --recursive 2>/dev/null | sed 's/^/  /' || echo "  (unavailable)"
    echo
    echo "tools:"
    for t in genus innovus calibre; do
        printf '  %-9s %s\n' "$t" "$(command -v $t 2>/dev/null || echo 'not on PATH')"
    done
    grep -m1 'Generated by' "$REP/${BLOCK}_imp_drc.rep" 2>/dev/null | sed 's/^# */  /' || true
    echo
    echo "geometry:"
    grep -m1 'set CORE_TO_IO' "$ASIC_DIR/scripts/floorplan.tcl" 2>/dev/null | sed 's/^/  /' || true
    grep -m1 'create_floorplan -site' "$ASIC_DIR/scripts/floorplan.tcl" 2>/dev/null | sed 's/^/  /' || true
    echo
    echo "contents (sha256):"
    ( cd "$STAGE" && find . -maxdepth 1 -type f ! -name MANIFEST.txt -print0 \
        | xargs -0 -r sha256sum | sed 's/^/  /' )
    echo
    cat <<'EOF'
-------------------------------------------------------------------------------
READ THIS BEFORE SUBMITTING
-------------------------------------------------------------------------------
1. THE GDS IS NOT SELF-CONTAINED.
   gds_merge_list (ASIC/genus-innovus/scripts/config.tcl) merges ONLY the 8
   memory macros, which ship with .gds2 locally. Standard cells (tcbn65lp), IO
   drivers (tphn65lpgv2od3_sl) and bond pads (tpbn65v) appear as EMPTY CELL
   REFERENCES: this site's PDK ships LEF/liberty/Milkyway but no GDS and no CDL
   for them. The recipient must merge the foundry cell libraries.

2. NO METAL DENSITY FILL HAS BEEN INSERTED.
   `add_metal_fill` appears nowhere in the flow. Standard-cell filler and
   ANTENNA diodes ARE inserted (see reports/*_imp_filler.rep), but per-layer
   metal density is unaddressed and will fail foundry density rules as-is.
   Agree explicitly who adds it.

3. LVS HAS NEVER BEEN RUN.
   It needs CDL for every leaf cell; only the memories have it here. Supply
   *_pnr.v to whoever holds the foundry data.

4. DRC IN reports/ IS NOT SIGNOFF DRC.
   It is Innovus check_drc over the incomplete GDS above: routing, PG and
   blockage geometry only.

5. NO SEAL RING OR SCRIBE IS INCLUDED.
   The die is 1600 x 2000 um with the pad ring starting at coordinate 0.
   Confirm who adds seal ring and scribe structures.

6. LOGICAL EQUIVALENCE (RTL vs post-P&R netlist) — confirm `make lec` has been
   run and passed for THIS netlist. A previous build silently lost an entire
   datapath to Genus GLO-34 unused-logic removal; LEC is the check that sees it.
-------------------------------------------------------------------------------
EOF
} > "$M"

# --- zip --------------------------------------------------------------------
( cd "$DEST" && zip -qr "$NAME.zip" "$NAME" )
rm -rf "$STAGE"

Z="$DEST/$NAME.zip"
echo "== $Z ($(du -h "$Z" | cut -f1)) =="
echo "$Z"
