################################################################################
# build_vivado.tcl — nanosoc_eth_chiplet on HAPS-SX VU19P, Vivado flow
#
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access
# license.
#
# Contributors
#
# David Mapstone (d.a.mapstone@soton.ac.uk)
#
# Copyright 2026, SoC Labs (www.soclabs.org)
################################################################################
# Run:  make -C fpga/haps-sx bitstream
#   or: vivado -mode batch -source fpga/haps-sx/scripts/build_vivado.tcl
#
# WHY VIVADO AND NOT PROTOSYNTHESIS
#
# The SX-native path is ProtoSynthesis (scripts/build_haps_sx.tcl), driven from
# the ProtoCompiler GUI. It is NOT usable at this site: `protocompiler_s`
# checks out the FlexNet feature `ProtoCompilerS`, which the licence server
# does not carry —
#
#     No such feature exists.
#     Feature:  ProtoCompilerS
#
# — and the licensed `protocompiler` product exposes only HAPS BOARD
# technologies (HAPS-200/100/SA3/80D/80/70/DX7/ZSA). There is no FPGA
# technology and no HAPS-SX entry, and forcing `-licensetype ProtoCompiler`
# onto protocompiler_s does not change that list.
#
# The VU19P is an ordinary AMD part, so Vivado can take the design all the way
# to a bitstream with no Synopsys licence. ConfPro-SX only consumes a .bit and
# does not care which tool produced it. The ProtoSynthesis scripts are kept in
# place for the day the licence appears — they share the .cob, the board top
# and the generated source list, so nothing here is throwaway.
#
# Fallback worth knowing: Synplify Premier DP IS licensed here and carries
# `HAPS-SX-VU19P-{20G,28G,32G}` targets natively (xilinx_parts.txt:5116). That
# keeps a Synopsys front end plus Identify instrumentation if this flow's
# inference ever proves inadequate.
################################################################################

set THIS_DIR [file dirname [file normalize [info script]]]
set HSX_DIR  [file dirname $THIS_DIR]
set BUILD    [file join $HSX_DIR build]
set OUT_DIR  [file join $BUILD vivado_out]
file mkdir $OUT_DIR

set TOP  nanosoc_eth_chiplet_haps_sx
set PART xcvu19p-fsva3824-2-e

# Parallelism; override with HAPS_SX_JOBS.
set JOBS 4
if { [info exists ::env(HAPS_SX_JOBS)] } { set JOBS $::env(HAPS_SX_JOBS) }

################################################################################
# Sources — generated by scripts/flist_to_sfl.py from the repo's own flists,
# so this can never drift from what `make elab` simulates.
################################################################################
set VIV_SRC [file join $BUILD chiplet_vivado.tcl]
if { ![file exists $VIV_SRC] } {
    error "Source list not generated. Run:  make -C $HSX_DIR srclist"
}
# The IMEM preload image. $readmemh resolves this relative name against
# Vivado's CWD, which the Makefile sets to build/. See the Makefile's
# `firmware` target for why it cannot be passed as a parameter.
if { ![file exists image.hex] || [file size image.hex] == 0 } {
    error "image.hex missing or empty in [pwd].\
Without it the IMEM preload fails, Vivado constant-folds the ROM away, and\
both cores HardFault on their first fetch — a board that looks dead with no\
other symptom. Run: make -C [file dirname $THIS_DIR] firmware"
}
puts "== IMEM preload: [file size image.hex] bytes of image.hex =="

puts "== reading sources =="
source $VIV_SRC

################################################################################
# Constraints — pins generated from the .cob, timing appended from the XDC.
################################################################################
set XDC [file join $BUILD ${TOP}.xdc]
if { ![file exists $XDC] } {
    error "Constraints not generated. Run:  make -C $HSX_DIR xdc"
}
read_xdc $XDC

# DRC waivers are SOURCED (not read_xdc'd) after routing — see below.
set DRC_TCL [file join $HSX_DIR constraints ${TOP}_drc.xdc]

################################################################################
# Synthesis
################################################################################
puts "== synth_design =="
synth_design -top $TOP -part $PART
write_checkpoint -force [file join $OUT_DIR post_synth.dcp]
report_utilization -file [file join $OUT_DIR post_synth_util.rpt]

# A black box here means an entire subsystem silently vanished from the
# netlist and the board will do nothing, with no error until bring-up.
set bboxes [get_cells -hier -quiet -filter {IS_BLACKBOX == 1}]
if { [llength $bboxes] > 0 } {
    puts "ERROR: [llength $bboxes] black box(es) in the synthesised netlist:"
    foreach b [lrange $bboxes 0 19] { puts "    [get_property REF_NAME $b]  ($b)" }
    error "Unresolved modules — check the source list before going further."
}

# Sanity-check that the memories inferred as block RAM.
#
# CALIBRATION NOTE: this SoC's memories are deliberately small (ASIC-driven):
# ETH bootrom/IMEM/DMEM = 8/32/16 KB, scratch RX/TX = 8/8 KB, CC IMEM/DMEM =
# 16/8 KB, and the CC bootrom is a synthesisable case-ROM (logic, not BRAM).
# ~88 KB of BRAM-backed memory plus MAC buffers, QSPI cache and TideLink FIFOs
# lands around 45 RAMB primitives / 32.5 tiles. A large shortfall means the
# memories fell back to distributed RAM or were optimised out.
#
# This does NOT detect a failed $readmemh preload: sl_fpga_rom_word has a live
# write port, so it is a RAM rather than a ROM and infers BRAM either way —
# only the INIT strings differ, and INIT content does not change resource
# counts. The preload is guarded separately by the image.hex check at the top
# of this script.
set n_bram [llength [get_cells -hier -quiet -filter {REF_NAME =~ RAMB*}]]
puts "== BRAM primitives inferred: $n_bram =="
if { $n_bram < 30 } {
    puts "WARNING: only $n_bram BRAM primitives — expected roughly 45 for this SoC."
    puts "         Suspect memories falling back to distributed RAM, or a"
    puts "         ram_style attribute not surviving synthesis."
}

################################################################################
# Debug ILA -- netlist insertion on the mark_debug UART/SWD/clock nets in the
# board top. Read over the ONBOARD FT232H JTAG (no external probe, no VTref).
# Clocked by sys_fclk (always alive). Re-added for SWD bring-up debug.
################################################################################
puts "== inserting debug ILA (u_ila_0) =="
create_debug_core u_ila_0 ila
set_property C_DATA_DEPTH 16384       [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN     false    [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN    false    [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER   false    [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 2    [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL  false    [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU true   [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1  [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets sys_fclk]
set dbg_bits {dbg_uart_txd dbg_uart_rxd dbg_swd_clk dbg_swd_tms dbg_swd_o \
              dbg_swd_oen dbg_hresetn dbg_poresetn dbg_net_lock dbg_chip_lock}
set i 0
foreach n $dbg_bits {
    if { $i > 0 } { create_debug_port u_ila_0 probe }
    set_property port_width 1 [get_debug_ports u_ila_0/probe$i]
    set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe$i]
    connect_debug_port u_ila_0/probe$i [get_nets $n]
    incr i
}
create_debug_port u_ila_0 probe
set_property port_width 8 [get_debug_ports u_ila_0/probe$i]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe$i]
connect_debug_port u_ila_0/probe$i [get_nets [list \
    {dbg_hclk_cnt[0]} {dbg_hclk_cnt[1]} {dbg_hclk_cnt[2]} {dbg_hclk_cnt[3]} \
    {dbg_hclk_cnt[4]} {dbg_hclk_cnt[5]} {dbg_hclk_cnt[6]} {dbg_hclk_cnt[7]}]]

################################################################################
# Implementation
################################################################################
puts "== opt / place / route =="
opt_design
if { [llength [get_debug_cores -quiet dbg_hub]] } {
    set_property C_CLK_INPUT_FREQ_HZ 25000000 [get_debug_cores dbg_hub]
    set_property C_ENABLE_CLK_DIVIDER false   [get_debug_cores dbg_hub]
    implement_debug_core
}
place_design
phys_opt_design
route_design

write_checkpoint -force  [file join $OUT_DIR post_route.dcp]
report_utilization    -file [file join $OUT_DIR post_route_util.rpt]
report_timing_summary -file [file join $OUT_DIR post_route_timing.rpt]
report_drc            -file [file join $OUT_DIR post_route_drc.rpt]

# Fail loudly on negative slack rather than shipping a bitstream that only
# sometimes works.
set wns [get_property SLACK [get_timing_paths -delay_type max]]
set whs [get_property SLACK [get_timing_paths -delay_type min]]
puts "== timing: WNS = $wns ns, WHS = $whs ns =="
if { $wns < 0 || $whs < 0 } {
    puts "WARNING: negative slack — the bitstream is NOT trustworthy."
    puts "         see [file join $OUT_DIR post_route_timing.rpt]"
}

################################################################################
# DRC waivers
#
# SOURCED as Tcl, not read_xdc'd, for two reasons:
#   * ALLOW_COMBINATORIAL_LOOPS has to land on nets in the ROUTED netlist, so
#     it must run after route_design, not at constraint-read time.
#   * the waiver file uses procedural Tcl (if / llength guards) to fail loudly
#     when the hierarchy moves, and Vivado rejects procedural Tcl inside an XDC
#     ([Designutils 20-1307]).
################################################################################
if { [file exists $DRC_TCL] } {
    puts "== applying DRC waivers =="
    source $DRC_TCL
} else {
    puts "WARNING: no DRC waiver file at $DRC_TCL — write_bitstream may fail on LUTLP-1."
}

################################################################################
# Bitstream
################################################################################
puts "== write_bitstream =="
write_bitstream -force [file join $OUT_DIR ${TOP}.bit]

# Probe map for the ILA (.ltx) -- Hardware Manager auto-loads it next to the .bit.
write_debug_probes -force [file join $OUT_DIR ${TOP}.ltx]

puts ""
puts "== DONE =="
puts "bitstream : [file join $OUT_DIR ${TOP}.bit]"
puts "program   : make -C $HSX_DIR program"
