################################################################################
# common.tcl — shared HAPS-SX setup for both the GUI and batch entry points
#
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access
# license.
#
# Contributors
#
# David Mapstone (d.a.mapstone@soton.ac.uk)
#
# Copyright 2026, SoC Labs (www.soclabs.org)
################################################################################
# Everything up to (but NOT including) the first `run` command lives here:
# locate the kit, generate pin constraints from the .cob, create/load the
# database, set options, register the source list.
#
# setup_gui.tcl sources this and stops, leaving the GUI staged so you drive the
# flow from the State menu. build_haps_sx.tcl sources this and then runs the
# whole flow headless. Neither duplicates the other's setup.
################################################################################

################################################################################
# 1. Locate ourselves and the project
################################################################################
set HSX_SCRIPTS  [file dirname [file normalize [info script]]]
set HSX_DIR      [file dirname $HSX_SCRIPTS]                    ;# fpga/haps-sx
set HSX_FPGA_DIR [file dirname $HSX_DIR]                        ;# fpga
set CHIPLET_HOME [file dirname $HSX_FPGA_DIR]                   ;# repo root

set HSX_BUILD    [file join $HSX_DIR build]
set HSX_VSRC     [file join $HSX_DIR vsrc]
set HSX_CONSTR   [file join $HSX_DIR constraints]

set TOP_MODULE   nanosoc_eth_chiplet_haps_sx
set DATABASE     [file join $HSX_BUILD ${TOP_MODULE}_db]
set VIVADO_DIR   [file join $HSX_BUILD vivado_pnr]
set RUNTIME_DIR  [file join $HSX_BUILD ${TOP_MODULE}_runtime]

file mkdir $HSX_BUILD

puts "INFO: HAPS-SX project root : $HSX_DIR"
puts "INFO: chiplet repo root    : $CHIPLET_HOME"

################################################################################
# 2. Locate the Synopsys HAPS-SX enablement kit
#
# The kit is Synopsys proprietary and is NOT vendored into this repo. Point
# COBRA_PATH at its haps-sx_helper directory (the `haps-sx-tools` modulefile
# does this for you). The cobra helper resolves the .def files relative to it.
#
# We source haps-sx_cobutil.tcl DIRECTLY rather than haps-sx_cobproc.tcl: the
# kit's cobproc.tcl has a COBRA_PATH lookup bug and only finds the helper in
# the current working directory.
################################################################################
if { [info exists ::env(COBRA_PATH)] && [file isdirectory $::env(COBRA_PATH)] } {
    set KIT_DIR [file normalize $::env(COBRA_PATH)]
} else {
    error "COBRA_PATH is not set. Run `module load haps-sx-tools`, or point\
COBRA_PATH at the HAPS-SX kit's 'haps-sx_helper' directory (it must contain\
haps-sx_cobutil.tcl and haps-sx_vu19p.def)."
}
if { ![file exists [file join $KIT_DIR haps-sx_cobutil.tcl]] } {
    error "HAPS-SX kit not found under COBRA_PATH=$KIT_DIR — no haps-sx_cobutil.tcl."
}
set ::env(COBRA_PATH) $KIT_DIR
source [file join $KIT_DIR haps-sx_cobutil.tcl]
puts "INFO: HAPS-SX kit          : $KIT_DIR"

################################################################################
# 3. Generate pin-location FDC from the .cob
################################################################################
set COB_FILE [file join $HSX_CONSTR ${TOP_MODULE}.cob]
set COB_FDC  [file join $HSX_BUILD  ${TOP_MODULE}_pins_generated.fdc]
if { ![file exists $COB_FILE] } {
    error "Missing pin map: $COB_FILE"
}
processCobFile $COB_FILE fdc $COB_FDC
puts "INFO: pin constraints      : $COB_FDC"

# The FDC list: generated pin locations first, then hand-written timing.
set TIMING_FDC [file join $HSX_CONSTR ${TOP_MODULE}.fdc]
set FDC_LIST   [file join $HSX_BUILD  ${TOP_MODULE}_fdc_list.sfl]
set fh [open $FDC_LIST w]
puts $fh "# Generated by common.tcl — DO NOT EDIT."
puts $fh $COB_FDC
if { [file exists $TIMING_FDC] } {
    puts $fh $TIMING_FDC
} else {
    puts "WARNING: no timing FDC at $TIMING_FDC — building unconstrained."
}
close $fh

################################################################################
# 4. Source list
#
# Generated by scripts/flist_to_sfl.py from the repo's own VCS flist, so it
# tracks the submodules automatically. `make srclist` regenerates it; we refuse
# to run against a stale or missing one rather than silently synthesising a
# subset of the design.
################################################################################
set SRC_LIST [file join $HSX_BUILD chiplet.sfl]
set INC_TCL  [file join $HSX_BUILD chiplet_inc.tcl]
if { ![file exists $SRC_LIST] || ![file exists $INC_TCL] } {
    error "Source list not generated. Run:  make -C $HSX_DIR srclist"
}

################################################################################
# 5. Database + options
################################################################################
database load $DATABASE -autocreate -technology Virtex-UltraScalePlus-FPGAs
source [file join $HSX_SCRIPTS options.tcl]

# include_path (semicolon-delimited) and HAPS_SX_HDL_DEFINES from the flist.
source $INC_TCL

################################################################################
# 6. Verilog defines
#
#   ETH_WISHBONE_B3 — selects the Wishbone-B3 protocol variant in the
#                     OpenCores MAC. The subsystem is wired for B3.
#   RAM_PRELOAD     — selects the ROM (sl_ahb_rom + $readmemh) variant of
#                     nanosoc_region_imem instead of a plain SRAM, so the IMEM
#                     carries firmware at configuration time. WITHOUT THIS the
#                     IMEM comes up empty and the CPU HardFaults on its first
#                     fetch — the single most common way to get a dead board.
################################################################################
set HDL_DEFINES [concat {ETH_WISHBONE_B3=1 RAM_PRELOAD=1} $HAPS_SX_HDL_DEFINES]
puts "INFO: hdl_define           : $HDL_DEFINES"

puts "INFO: top module           : $TOP_MODULE"
puts "INFO: source list          : $SRC_LIST"
puts "INFO: fdc list             : $FDC_LIST"
puts "INFO: setup complete."
