#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# fdc_to_xdc.py — convert the HAPS-SX kit's generated FDC into valid Vivado XDC
#
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access
# license.
#
# Contributors
#
# David Mapstone (d.a.mapstone@soton.ac.uk)
#
# Copyright 2026, SoC Labs (www.soclabs.org)
# -----------------------------------------------------------------------------
# WHY NOT JUST USE THE KIT'S XDC MODE
#
# The kit helper can emit XDC directly (`processCobFile <cob> xdc <out>`), but
# its output is not usable as-is:
#
#   1. Bus bits are emitted unbraced — `[get_ports pmod1[0] ]`. Tcl evaluates
#      the inner `[0]` as a command substitution, so the constraint either
#      errors or silently matches nothing.
#   2. `define_io_standard` is dropped entirely, so every pin arrives at
#      placement with no IOSTANDARD and fails DRC.
#
# So we let the kit do the part it is authoritative about — resolving symbolic
# board resources (DBG.PMOD.PMOD1.0, MEM.FLASH.CLK, ...) to package pins
# against haps-sx_vu19p.def — and convert its FDC output here. Pin data still
# comes from Synopsys; only the syntax is ours.
#
# I/O STANDARD MAPPING
#
# Synplify spells its pad types with an underscore and a voltage suffix; Vivado
# does not. Note LVDS in particular: on a High-Performance bank the Vivado name
# is plain `LVDS` (1.8 V), NOT `LVDS_25` — the latter is the High-Density-bank
# spelling and Vivado rejects it on an HP bank.
#
# USAGE
#   fdc_to_xdc.py <generated.fdc> -o <out.xdc> [--extra <file.xdc>]
# -----------------------------------------------------------------------------

import argparse
import re
import sys

# Synplify syn_pad_type -> Vivado IOSTANDARD
IOSTD_MAP = {
    "LVCMOS_12": "LVCMOS12",
    "LVCMOS_15": "LVCMOS15",
    "LVCMOS_18": "LVCMOS18",
    "LVCMOS_25": "LVCMOS25",
    "LVCMOS_33": "LVCMOS33",
    "LVDS_18":   "LVDS",       # HP bank differential; NOT LVDS_25
    "LVDS_25":   "LVDS_25",    # HD bank differential
    "LVTTL":     "LVTTL",
    "SSTL_15":   "SSTL15",
    "SSTL_12":   "SSTL12",
}

# define_attribute {p:name}  xc_loc PIN
RE_LOC = re.compile(
    r"^\s*define_attribute\s*\{\s*p:([^}]+?)\s*\}\s*xc_loc\s+(\S+)", re.I)

# define_io_standard {p:name} syn_pad_type {STD} [-delay_type {dir}]
RE_STD = re.compile(
    r"^\s*define_io_standard\s*\{\s*p:([^}]+?)\s*\}\s*syn_pad_type\s*\{\s*(\S+?)\s*\}", re.I)


def brace(port):
    """Wrap a port name for get_ports, bracing it if it is a bus bit.

    `foo[0]` must become `{foo[0]}` or Tcl treats `[0]` as a command.
    """
    return "{%s}" % port if "[" in port else port


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("fdc", help="FDC generated by the kit's processCobFile")
    ap.add_argument("-o", "--out", required=True, help="output XDC")
    ap.add_argument("--extra", action="append", default=[],
                    help="XDC fragment appended verbatim (timing, cfg, ...)")
    args = ap.parse_args()

    locs = {}       # port -> package pin
    stds = {}       # port -> IOSTANDARD
    order = []      # preserve declaration order for readable output
    unknown = []

    with open(args.fdc) as fh:
        for line in fh:
            if line.lstrip().startswith("#"):
                continue

            m = RE_LOC.match(line)
            if m:
                port, pin = m.group(1).strip(), m.group(2).strip()
                if port not in locs:
                    order.append(port)
                locs[port] = pin
                continue

            m = RE_STD.match(line)
            if m:
                port, std = m.group(1).strip(), m.group(2).strip()
                mapped = IOSTD_MAP.get(std.upper())
                if mapped is None:
                    unknown.append((port, std))
                else:
                    stds[port] = mapped

    if unknown:
        sys.stderr.write(
            "fdc_to_xdc: %d port(s) use a syn_pad_type with no Vivado "
            "equivalent in IOSTD_MAP — add it there:\n" % len(unknown))
        for port, std in unknown[:20]:
            sys.stderr.write("    %-28s %s\n" % (port, std))
        return 1

    # A pin with no IOSTANDARD reaches placement unconstrained and fails DRC
    # with an error that does not name this file. Catch it here instead.
    missing_std = [p for p in order if p not in stds]
    if missing_std:
        sys.stderr.write(
            "fdc_to_xdc: %d port(s) have a pin location but no "
            "define_io_standard — Vivado will fail DRC:\n" % len(missing_std))
        for p in missing_std[:20]:
            sys.stderr.write("    %s\n" % p)
        return 1

    with open(args.out, "w") as fh:
        fh.write("#" * 78 + "\n")
        fh.write("# Generated by fdc_to_xdc.py from %s\n" % args.fdc)
        fh.write("# DO NOT EDIT — regenerate with `make xdc`.\n")
        fh.write("# Pin locations resolved by the Synopsys HAPS-SX kit helper\n")
        fh.write("# against haps-sx_vu19p.def; syntax converted here.\n")
        fh.write("#" * 78 + "\n\n")
        for port in order:
            fh.write("set_property -dict {PACKAGE_PIN %s IOSTANDARD %s} [get_ports %s]\n"
                     % (locs[port], stds[port], brace(port)))

        for extra in args.extra:
            fh.write("\n" + "#" * 78 + "\n")
            fh.write("# Appended verbatim from %s\n" % extra)
            fh.write("#" * 78 + "\n")
            with open(extra) as ex:
                fh.write(ex.read())

    sys.stderr.write("fdc_to_xdc: %d pins -> %s\n" % (len(order), args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
