#!/usr/bin/env python3
#-----------------------------------------------------------------------------
# flatten_soc_flist.py — make the SoC's generated flist VCS-readable.
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access
# license.  Copyright 2026, SoC Labs (www.soclabs.org)
#-----------------------------------------------------------------------------
# WHY THIS EXISTS
#
# nanosoc_gen emits its per-module filelists (build_soc/flist/*.flist) from
# Jinja templates that write Makefile-style `$(VAR)` paths. VCS expands `${VAR}`
# and `$VAR` but NOT `$(VAR)`, so it treats those paths as literal and fails
# with Error-[SFCOR]. The repo ships a hand-maintained flat `${}`-syntax flist
# (nanosoc_multicore_generic.flist) to work around this — but it lags the
# generated RTL (it still names DMA_230_0 / CPU_*_DBG_WINDOW after the D2D
# regen renamed them to DMAC_0 / {NETWORK,CHIP}_CORE_*), so it cannot open the
# current build_soc.
#
# Rather than fork either flist (both live in the READ-ONLY SoC submodule),
# this script consumes the IN-SYNC generated flist (nanosoc_multicore.flist,
# which `-f`-includes the freshly rendered build_soc/flist/*.flist) and emits a
# single flat, fully-resolved flist VCS can read. It is regenerated on every
# `make elab`, so it can never go stale against build_soc.
#
# Transform: inline every `-f` include (one level; the generated leaf flists
# nest no further), rewrite `$(VAR)` -> `${VAR}`, and expand all variables to
# absolute paths against the current environment.
#
# Usage: flatten_soc_flist.py <root.flist> > <out.f>
#-----------------------------------------------------------------------------
import os, re, sys

def convert(tok):
    # $(VAR) -> ${VAR}, then expand ${VAR}/$VAR against the environment.
    tok = re.sub(r'\$\(([A-Za-z_]\w*)\)', r'${\1}', tok)
    return os.path.expandvars(tok)

def flatten(path, out, seen):
    ap = os.path.abspath(path)
    if ap in seen:                      # guard against accidental cycles
        return
    seen.add(ap)
    with open(ap) as fh:
        for raw in fh:
            line = raw.split('//', 1)[0].rstrip()   # drop line comments
            s = line.strip()
            if not s:
                continue
            m = re.match(r'-f\s+(\S+)', s)
            if m:
                flatten(convert(m.group(1)), out, seen)
            else:
                out.append(convert(s))

if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit("usage: flatten_soc_flist.py <root.flist>")
    lines = []
    flatten(sys.argv[1], lines, set())
    print("// AUTO-GENERATED by flatten_soc_flist.py — do not edit; regenerated each build.")
    print("\n".join(lines))
