#!/usr/bin/env python3
#-----------------------------------------------------------------------------
# flatten_soc_flist.py — make the SoC's generated flist VCS-readable.
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access
# license.  Copyright 2026, SoC Labs (www.soclabs.org)
#-----------------------------------------------------------------------------
# WHAT IT DOES
#
# Reads the SoC's generated root flist (nanosoc_multicore.flist, which
# `-f`-includes the freshly rendered build_soc/flist/*.flist) and writes ONE
# flat, fully-resolved file list on stdout.
#
# Transform: inline every `-f` include (one level; the generated leaf flists
# nest no further), rewrite `$(VAR)` -> `${VAR}`, and expand all variables to
# absolute paths against the current environment.
#
# The rewrite is the point. nanosoc_gen renders its filelists from Jinja
# templates that emit Makefile-style `$(VAR)` paths; VCS expands `${VAR}` and
# `$VAR` but NOT `$(VAR)`, so it reads those paths literally and fails with
# Error-[SFCOR]. The SoC submodule also ships a hand-maintained flat flist, but
# it is maintained separately from the generated RTL and drifts out of step with
# module renames. Consuming the GENERATED flist instead, and regenerating on
# every `make elab`, means this output cannot go stale against build_soc. The
# SoC submodule is read-only from here, so neither of its flists is forked.
#
# Usage: flatten_soc_flist.py <root.flist> > <out.f>
# Exit:  0 written; 1 wrong argument count. A missing or unreadable flist
#        raises, so a broken include is never silently dropped.
#-----------------------------------------------------------------------------
import os, re, sys

def convert(tok):
    """Rewrite $(VAR) to ${VAR}, then expand ${VAR}/$VAR against the environment."""
    tok = re.sub(r'\$\(([A-Za-z_]\w*)\)', r'${\1}', tok)
    return os.path.expandvars(tok)

def flatten(path, out, seen):
    """Append `path`'s entries to `out`, recursing into every `-f` include."""
    ap = os.path.abspath(path)
    if ap in seen:                      # guard against accidental cycles
        return
    seen.add(ap)
    with open(ap) as fh:
        for raw in fh:
            line = raw.split('//', 1)[0].rstrip()   # drop line comments
            s = line.strip()
            if not s:
                continue
            m = re.match(r'-f\s+(\S+)', s)
            if m:
                flatten(convert(m.group(1)), out, seen)
            else:
                out.append(convert(s))

if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit("usage: flatten_soc_flist.py <root.flist>")
    lines = []
    flatten(sys.argv[1], lines, set())
    print("// AUTO-GENERATED by flatten_soc_flist.py — do not edit; regenerated each build.")
    print("\n".join(lines))
