#!/usr/bin/env python3
"""Emit a TideLink filelist with EXACTLY ONE definition of every module.

Copyright 2026, SoC Labs (www.soclabs.org)

Why this exists
---------------
`tidelink/flists/tidelink_fpga.flist` is internally inconsistent at the commit we
pin. It compiles the `deps/` copy of `WlinkGenericFCReplayAddrSync_18`, which has
no `obs_*` ports, AND the local override `WlinkGenericFCReplayV2_13`, which
drives those ports. Compiling it as-shipped gives 7x `Error-[UPIMI-E]`.

The obvious workaround is to append TideLink's own override
(`src/rtl/local_overrides/WlinkGenericFCReplayAddrSync_18.v`) and rely on VCS's
"last declaration wins", which is what TideLink does internally. **That is not
safe here.** It makes the effective netlist a property of the TOOL, not of the
filelist:

  * VCS       — last wins. You get the override. (Only a `Warning-[OPD]`.)
  * Verilator — duplicate module is an error.
  * Some Xcelium / Icarus modes — FIRST declaration wins.

A first-wins tool binds the `deps/` copy **silently**. The override is not
cosmetic: it carries the a2l ACK-ptr reset-skew fix (async-assert /
sync-deassert of `w_reset` into `r_clk`). Its own header records that an
idealised single-clock simulation "resolves the demets cleanly and never exposes
it" — so a green sim proves nothing about whether the fix is even present.

Losing that fix on silicon reappears as the a2l 6-word cap / false-FULL wedge:
the link delivers a handful of writes and stops. Discovering that on a chiplet,
after tape-out, because lint and synthesis picked a different module than the
simulator did, is not a debugging session anyone should have.

So we do not rely on ordering. We REMOVE the deps copy from the filelist and
append the override, leaving exactly one definition for every tool.

The right long-term fix is upstream: swap the `deps/` path for the override in
`tidelink/flists/tidelink_fpga.flist` (its siblings `tidelink_fpga_v2` and
`tidelink_a2l_replay_cdc` already do). Until that lands, this script is the seam.

Usage
-----
    resolve_tidelink_flist.py <tidelink_fpga.flist> > resolved.f

`-f` includes are expanded recursively so the result is flat and every path is
absolute. Environment variables in paths are expanded.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

# Modules whose `deps/` copy must never be compiled, because a local override
# supersedes it. basename -> the override that replaces it (relative to TIDELINK_HOME).
SHADOWED = {
    "WlinkGenericFCReplayAddrSync_18.v":
        "src/rtl/local_overrides/WlinkGenericFCReplayAddrSync_18.v",
}


def expand(tok: str) -> str:
    return os.path.expandvars(tok).strip()


def read_flist(path: Path, seen: set[Path], out: list[str], dropped: list[str]) -> None:
    path = path.resolve()
    if path in seen:
        return
    seen.add(path)
    base = path.parent

    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("//") or line.startswith("#"):
            continue

        if line.startswith("-f "):
            inc = Path(expand(line[3:].strip()))
            if not inc.is_absolute():
                inc = base / inc
            read_flist(inc, seen, out, dropped)
            continue

        # Pass compiler switches through untouched.
        if line.startswith(("-", "+")):
            out.append(line)
            continue

        p = expand(line)
        name = os.path.basename(p)
        if name in SHADOWED and f"{os.sep}deps{os.sep}" in p:
            dropped.append(p)
            continue
        out.append(p)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    tl_home = os.environ.get("TIDELINK_HOME")
    if not tl_home:
        print("resolve_tidelink_flist: TIDELINK_HOME is not set", file=sys.stderr)
        return 1

    out: list[str] = []
    dropped: list[str] = []
    read_flist(Path(expand(sys.argv[1])), set(), out, dropped)

    if not dropped:
        print("resolve_tidelink_flist: WARNING — expected to drop a shadowed deps "
              "module and dropped none. Has the upstream flist been fixed? If so, "
              "delete this script.", file=sys.stderr)

    for p in dropped:
        print(f"resolve_tidelink_flist: dropped shadowed {p}", file=sys.stderr)

    # Append every override that replaced something we dropped.
    for name, rel in SHADOWED.items():
        if any(os.path.basename(d) == name for d in dropped):
            ov = Path(tl_home) / rel
            if not ov.is_file():
                print(f"resolve_tidelink_flist: MISSING override {ov}", file=sys.stderr)
                return 1
            if str(ov) not in out:
                out.append(str(ov))

    print("// Generated by flist/resolve_tidelink_flist.py — do not edit.")
    print("// Exactly one definition per module; no reliance on tool declaration order.")
    for line in out:
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
