#!/usr/bin/env bash
#-----------------------------------------------------------------------------
# verif/bscan/run.sh -- the IEEE 1149.1 boundary-scan gate, under VCS.
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access license.
#
# Copyright 2026, SoC Labs (www.soclabs.org)
#-----------------------------------------------------------------------------
#   source ../../set_env.sh && ./run.sh          # ~5 s
#
# WHAT IT GATES
#   nanosoc_eth_chiplet_bscan (src/rtl/bscan/) against INTERFACE_CONTRACT.md:
#   functional transparency with the TAP disabled, TAP reset, IDCODE, BYPASS,
#   the 76-cell chain length, SAMPLE, EXTEST, and the open-drain I2C rule.
#   tb_bscan.sv prints one comparison count and one verdict; this script decides
#   whether that verdict is allowed to mean anything.
#
# WHY THE VERDICT IS NOT JUST `$?`
#   VCS's simv exits 0 on `$finish` whatever the bench decided, so the exit code
#   of the simulation says nothing at all about the design. Worse, the failure
#   modes that actually happen here are the silent ones: a bench that elaborated
#   and then died in the first microsecond, or one shortened with +nrand until
#   it measures nothing, both print no failures. So the gate is three-part:
#     1. the machine-readable summary line must EXIST (a run that vanished
#        cannot be a pass);
#     2. every test must have run  (tests=N/N, N >= 11);
#     3. the bench must report a plausible NUMBER OF COMPARISONS. A full run is
#        ~40,000; the floor below is well under that and far above anything a
#        truncated run reaches. A zero that measured nothing is not a zero.
#
# EXIT CODES
#   0  pass          2  setup problem (no RTL, generator refused, no VCS)
#   1  test failure  3  compile/elaboration failure
#
# ENV
#   BSCAN_RTL_DIR    default $CHIPLET_HOME/src/rtl/bscan
#   BSCAN_BUILD      default $HERE/build   (relocatable: two lanes cannot collide)
#   BSCAN_MIN_CHECKS default 30000         (raise/lower only with a reason)
#   VCS              default `vcs` on PATH
#   extra args are passed to simv, e.g.  ./run.sh +seed=7 +idcode=100005a1
#-----------------------------------------------------------------------------
# NOT `set -u`: the component set_env.sh scripts reference positional args.
set -eo pipefail

HERE="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
CHIPLET_HOME="$(cd "$HERE/../.." && pwd)"

VCS="${VCS:-vcs}"
BSCAN_RTL_DIR="${BSCAN_RTL_DIR:-$CHIPLET_HOME/src/rtl/bscan}"
BUILD="${BSCAN_BUILD:-$HERE/build}"
MIN_CHECKS="${BSCAN_MIN_CHECKS:-30000}"
TOP=tb_bscan

[ -f "$CHIPLET_HOME/set_env.sh" ] && source "$CHIPLET_HOME/set_env.sh" >/dev/null

if ! command -v "$VCS" >/dev/null 2>&1; then
    echo "== bscan SETUP FAIL: '$VCS' is not on PATH. Set VCS=/path/to/vcs. =="
    exit 2
fi

# ---------------------------------------------------------------------------
# STALE-BUILD TRAP. VCS happily re-runs yesterday's simv when today's compile
# fails in a way the script does not notice, and the bench then reports a green
# for RTL that is not on disk any more. The build directory is destroyed on
# every run; there is no incremental mode and there should not be one.
# ---------------------------------------------------------------------------
rm -rf "$BUILD"
mkdir -p "$BUILD"

# ---------------------------------------------------------------------------
# 1. RTL. The wrapper is generated by scripts/gen_bscan.py from pad_table.json;
#    if nobody has generated it yet, say exactly that rather than emitting 150
#    "module not found" errors.
# ---------------------------------------------------------------------------
shopt -s nullglob
RTL=( "$BSCAN_RTL_DIR"/*.sv "$BSCAN_RTL_DIR"/*.v )
shopt -u nullglob
if [ "${#RTL[@]}" -eq 0 ]; then
    echo "== bscan SETUP FAIL: no RTL in $BSCAN_RTL_DIR =="
    echo "   Expected bscan_cell.sv, bscan_tap.sv, bscan_ir.sv and the generated"
    echo "   nanosoc_eth_chiplet_bscan.sv (scripts/gen_bscan.py, from pad_table.json)."
    echo "   Point BSCAN_RTL_DIR elsewhere to run this bench against another tree."
    exit 2
fi
if ! grep -qsE '\bmodule\s+nanosoc_eth_chiplet_bscan\b' "${RTL[@]}"; then
    echo "== bscan SETUP FAIL: no module nanosoc_eth_chiplet_bscan in $BSCAN_RTL_DIR =="
    echo "   found: $(basename -a "${RTL[@]}" | tr '\n' ' ')"
    exit 2
fi

# ---------------------------------------------------------------------------
# 2. Regenerate the pad header from pad_table.json ON EVERY RUN, so this bench
#    can never be testing a ring order the table no longer describes. The
#    generator also carries the STATIC half of the open-drain rule (contract
#    section 1): it refuses to emit if the wrapper declares a data path on
#    uPAD_I2C_SCL / uPAD_I2C_SDA. A TB cannot see a port it does not connect,
#    so that check has to live here, and it has to be able to stop the run.
# ---------------------------------------------------------------------------
echo "== generating tb_bscan_pads.svh from src/rtl/bscan/pad_table.json =="
if ! python3 "$HERE/gen_tb_pads.py" --rtl-dir "$BSCAN_RTL_DIR" \
        --out "$BUILD/tb_bscan_pads.svh" 2>&1 | sed 's/^/   /'; then
    echo "== bscan SETUP FAIL: gen_tb_pads.py refused to emit a header (see above) =="
    exit 2
fi

# ---------------------------------------------------------------------------
# 3. Compile.
# ---------------------------------------------------------------------------
VLOG="$BUILD/vcs.log"
echo "== vcs: compiling $TOP over ${#RTL[@]} RTL file(s) =="
set +e
( cd "$BUILD" && "$VCS" -full64 -sverilog -timescale=1ns/1ps -q \
      +incdir+"$BUILD" \
      "${RTL[@]}" "$HERE/tb_bscan.sv" \
      -top "$TOP" -o "$BUILD/simv" -l "$VLOG" ) >/dev/null 2>&1
vcs_rc=$?
set -e
if [ "$vcs_rc" -ne 0 ] || [ ! -x "$BUILD/simv" ]; then
    echo "== bscan COMPILE FAIL (rc=$vcs_rc) =="
    grep -aE '^(Error|Warning)-\[|^Error|\*E,' "$VLOG" 2>/dev/null | head -25 | sed 's/^/   /'
    echo "   log: $VLOG"
    exit 3
fi

# ---------------------------------------------------------------------------
# 4. Run.
# ---------------------------------------------------------------------------
SLOG="$BUILD/sim.log"
echo "== simv: running the bench =="
set +e
( cd "$BUILD" && timeout "${BSCAN_TIMEOUT:-900}" ./simv -l "$SLOG" "$@" ) >/dev/null 2>&1
sim_rc=$?
set -e
if [ "$sim_rc" -eq 124 ] || [ "$sim_rc" -eq 137 ]; then
    echo "== bscan FAIL: simv was KILLED at ${BSCAN_TIMEOUT:-900}s wall clock =="
    echo "   Nothing below can be read as a result. log: $SLOG"
    exit 1
fi

sed -n '/^--- T/,$p' "$SLOG" 2>/dev/null | grep -avE '^\$finish|^ *$' | sed 's/^/   /' || true

# ---------------------------------------------------------------------------
# 5. Verdict -- see "WHY THE VERDICT IS NOT JUST $?" above.
# ---------------------------------------------------------------------------
SUMMARY="$(grep -a '^BSCAN_SUMMARY:' "$SLOG" 2>/dev/null | tail -1 || true)"
if [ -z "$SUMMARY" ]; then
    echo "== bscan FAIL: the bench printed NO summary line =="
    echo "   It did not reach the end of its stimulus, so there is no verdict to read."
    echo "   simv rc=$sim_rc. log: $SLOG"
    tail -15 "$SLOG" 2>/dev/null | sed 's/^/   /'
    exit 1
fi

VERDICT="$(sed -n 's/^BSCAN_SUMMARY: \([A-Z]*\).*/\1/p'      <<<"$SUMMARY")"
CHECKS="$( sed -n 's/.*checks=\([0-9]*\).*/\1/p'              <<<"$SUMMARY")"
FAILS="$(  sed -n 's/.*fails=\([0-9]*\).*/\1/p'               <<<"$SUMMARY")"
TPASS="$(  sed -n 's/.*tests=\([0-9]*\)\/[0-9]*.*/\1/p'       <<<"$SUMMARY")"
TTOT="$(   sed -n 's/.*tests=[0-9]*\/\([0-9]*\).*/\1/p'       <<<"$SUMMARY")"

echo
echo "== $SUMMARY =="

if [ "$VERDICT" != "PASS" ] || [ "${FAILS:-1}" -ne 0 ]; then
    echo "== bscan FAIL: $FAILS failing comparison(s) across $((TTOT - TPASS)) test(s) =="
    grep -aE '^    FAIL' "$SLOG" | head -25 | sed 's/^/   /'
    echo "   full log: $SLOG"
    exit 1
fi
if [ "${TTOT:-0}" -lt 11 ] || [ "${TPASS:-0}" -ne "${TTOT:-0}" ]; then
    echo "== bscan FAIL: only $TPASS of $TTOT tests passed, and the bench defines >= 11 =="
    echo "   log: $SLOG"
    exit 1
fi
if [ "${CHECKS:-0}" -lt "$MIN_CHECKS" ]; then
    echo "== bscan FAIL: only $CHECKS comparisons were performed (floor $MIN_CHECKS) =="
    echo "   A green over a stimulus this short is not evidence. If the run was"
    echo "   deliberately shortened (+nrand=...), it is a debug run, not the gate."
    echo "   log: $SLOG"
    exit 1
fi

echo "== bscan OK: $TTOT/$TTOT tests, $CHECKS comparisons, 0 failures =="
echo "   log: $SLOG"
